"""Instrument catalog.

Leverage caps follow typical EU retail (ESMA) limits so beginners learn realistic
constraints: crypto 2:1, major FX 30:1, minor FX 20:1, major indices 20:1,
gold 20:1, other commodities 10:1, stocks 5:1.

`anchor_price`, `daily_vol`, `daily_volume_usd` and `drift` only parameterise the
DEMO (synthetic) data generator — they are not real market statistics.
"""

from __future__ import annotations

from app.market.base import AssetSpec

_CRYPTO_FEES = {"maker_fee": 0.0002, "taker_fee": 0.0006}
_FX_FEES = {"maker_fee": 0.00003, "taker_fee": 0.00003}
_CFD_FEES = {"maker_fee": 0.0, "taker_fee": 0.0}
_STOCK_FEES = {"maker_fee": 0.0005, "taker_fee": 0.0005}

ASSETS: list[AssetSpec] = [
    AssetSpec(
        "BTC/USDT",
        "Bitcoin",
        "crypto",
        2,
        0.0001,
        0.0001,
        1.0,
        **_CRYPTO_FEES,
        max_leverage=2,
        anchor_price=95_000,
        daily_vol=0.030,
        daily_volume_usd=2.0e10,
        drift=0.0006,
        provider_symbols={"binance": "BTCUSDT", "twelvedata": "BTC/USD"},
        description="Най-голямата криптовалута по пазарна капитализация. Търгува 24/7.",
    ),
    AssetSpec(
        "ETH/USDT",
        "Ethereum",
        "crypto",
        2,
        0.001,
        0.001,
        1.5,
        **_CRYPTO_FEES,
        max_leverage=2,
        anchor_price=3_400,
        daily_vol=0.040,
        daily_volume_usd=1.0e10,
        drift=0.0006,
        provider_symbols={"binance": "ETHUSDT", "twelvedata": "ETH/USD"},
        description="Втората по големина криптовалута; платформа за smart contracts.",
    ),
    AssetSpec(
        "SOL/USDT",
        "Solana",
        "crypto",
        3,
        0.01,
        0.01,
        3.0,
        **_CRYPTO_FEES,
        max_leverage=2,
        anchor_price=190,
        daily_vol=0.055,
        daily_volume_usd=2.0e9,
        drift=0.0007,
        provider_symbols={"binance": "SOLUSDT", "twelvedata": "SOL/USD"},
        description="Високоволатилна криптовалута — добър пример за риск и размер на позицията.",
    ),
    AssetSpec(
        "XRP/USDT",
        "XRP",
        "crypto",
        4,
        1.0,
        1.0,
        4.0,
        **_CRYPTO_FEES,
        max_leverage=2,
        anchor_price=2.2,
        daily_vol=0.050,
        daily_volume_usd=1.5e9,
        drift=0.0004,
        provider_symbols={"binance": "XRPUSDT", "twelvedata": "XRP/USD"},
        description="Криптовалута с ниска цена на единица — внимавай с броя единици.",
    ),
    AssetSpec(
        "EUR/USD",
        "Euro / US Dollar",
        "forex",
        5,
        100.0,
        1000.0,
        0.8,
        **_FX_FEES,
        max_leverage=30,
        anchor_price=1.10,
        daily_vol=0.005,
        daily_volume_usd=1.0e11,
        drift=0.0,
        provider_symbols={"twelvedata": "EUR/USD"},
        description="Най-търгуваната валутна двойка. Ниска волатилност, но често се търгува с leverage.",
    ),
    AssetSpec(
        "GBP/USD",
        "British Pound / US Dollar",
        "forex",
        5,
        100.0,
        1000.0,
        1.2,
        **_FX_FEES,
        max_leverage=30,
        anchor_price=1.30,
        daily_vol=0.006,
        daily_volume_usd=5.0e10,
        drift=0.0,
        provider_symbols={"twelvedata": "GBP/USD"},
        description='"Cable" — малко по-волатилна от EUR/USD.',
    ),
    AssetSpec(
        "AUD/USD",
        "Australian Dollar / US Dollar",
        "forex",
        5,
        100.0,
        1000.0,
        1.5,
        **_FX_FEES,
        max_leverage=20,
        anchor_price=0.66,
        daily_vol=0.007,
        daily_volume_usd=3.0e10,
        drift=0.0,
        provider_symbols={"twelvedata": "AUD/USD"},
        description="Валута, чувствителна към суровини и риск апетит.",
    ),
    AssetSpec(
        "XAU/USD",
        "Gold",
        "commodity",
        2,
        0.01,
        0.01,
        2.0,
        **_CFD_FEES,
        max_leverage=20,
        anchor_price=2_650,
        daily_vol=0.009,
        daily_volume_usd=2.0e10,
        drift=0.0002,
        provider_symbols={"twelvedata": "XAU/USD"},
        description="Златото — класически 'safe haven' актив. Цена за тройунция.",
    ),
    AssetSpec(
        "WTI/USD",
        "WTI Crude Oil",
        "commodity",
        2,
        0.1,
        0.1,
        4.0,
        **_CFD_FEES,
        max_leverage=10,
        anchor_price=72,
        daily_vol=0.022,
        daily_volume_usd=1.0e10,
        drift=0.0,
        provider_symbols={"twelvedata": "WTI/USD"},
        description="Петрол — силно зависим от новини и геополитика.",
    ),
    AssetSpec(
        "SPX",
        "S&P 500",
        "index",
        2,
        0.01,
        0.01,
        1.0,
        **_CFD_FEES,
        max_leverage=20,
        anchor_price=6_000,
        daily_vol=0.010,
        daily_volume_usd=2.0e10,
        drift=0.0003,
        provider_symbols={"twelvedata": "SPX"},
        description="Индекс на 500 големи американски компании (CFD, $1 на точка).",
    ),
    AssetSpec(
        "NDX",
        "NASDAQ 100",
        "index",
        2,
        0.01,
        0.01,
        1.2,
        **_CFD_FEES,
        max_leverage=20,
        anchor_price=21_500,
        daily_vol=0.013,
        daily_volume_usd=1.5e10,
        drift=0.0004,
        provider_symbols={"twelvedata": "NDX"},
        description="Технологично натоварен индекс на 100 компании (CFD, $1 на точка).",
    ),
    AssetSpec(
        "GER40",
        "Germany 40 (DAX)",
        "index",
        1,
        0.01,
        0.01,
        1.5,
        **_CFD_FEES,
        max_leverage=20,
        anchor_price=20_000,
        daily_vol=0.011,
        daily_volume_usd=5.0e9,
        drift=0.0003,
        provider_symbols={"twelvedata": "DAX"},
        description="Германският индекс DAX (CFD, котиран в USD за симулацията).",
    ),
    AssetSpec(
        "AAPL",
        "Apple",
        "stock",
        2,
        0.01,
        0.01,
        2.0,
        **_STOCK_FEES,
        max_leverage=5,
        anchor_price=245,
        daily_vol=0.017,
        daily_volume_usd=1.0e10,
        drift=0.0004,
        provider_symbols={"twelvedata": "AAPL"},
        description="Акция (CFD) — голяма, ликвидна компания.",
    ),
    AssetSpec(
        "TSLA",
        "Tesla",
        "stock",
        2,
        0.01,
        0.01,
        3.0,
        **_STOCK_FEES,
        max_leverage=5,
        anchor_price=380,
        daily_vol=0.035,
        daily_volume_usd=2.0e10,
        drift=0.0004,
        provider_symbols={"twelvedata": "TSLA"},
        description="Силно волатилна акция — добър пример за широки стопове.",
    ),
    AssetSpec(
        "NVDA",
        "NVIDIA",
        "stock",
        2,
        0.01,
        0.01,
        2.5,
        **_STOCK_FEES,
        max_leverage=5,
        anchor_price=140,
        daily_vol=0.030,
        daily_volume_usd=3.0e10,
        drift=0.0006,
        provider_symbols={"twelvedata": "NVDA"},
        description="Акция с голям momentum в миналото — внимавай с recency bias.",
    ),
]

ASSETS_BY_SYMBOL: dict[str, AssetSpec] = {a.symbol: a for a in ASSETS}

DEFAULT_WATCHLIST = ["BTC/USDT", "ETH/USDT", "SOL/USDT", "EUR/USD", "XAU/USD", "SPX", "NDX"]


class UnknownAssetError(KeyError):
    pass


def get_asset(symbol: str) -> AssetSpec:
    try:
        return ASSETS_BY_SYMBOL[symbol]
    except KeyError as exc:
        raise UnknownAssetError(symbol) from exc
