"""Commodities (spot metals and energy CFDs; agricultural CFDs are demo-only).

Reference data only: plain dict literals, no imports from the app.
* Twelve Data symbols were validated against /commodities, which lists only metals (XAU, XAG, XPT, XPD, HG1 copper)
  and oil (WTI/USD, XBR/USD Brent, URALS/USD). Natural gas and all agricultural products (corn, wheat, soybeans,
  coffee, cocoa, sugar, cotton) are not available there, so they carry no provider mapping and are demo-only.
  Heating oil and gasoline were left out for the same reason.
* Units: metals per troy ounce (copper per lb), oil per barrel, gas per MMBtu, grains per bushel, softs per lb
  (cocoa per metric ton). All prices in USD.
* `session` uses the CME Globex-style calendar for every row (close to real hours for metals/energy; ICE softs and
  CBOT grains really trade shorter sessions).
* `demo` only parameterises the clearly-labelled SYNTHETIC demo generator: anchor_price is an approximate
  level around 2026-01-01; daily_vol / daily_volume_usd / drift are rough illustrative values, not statistics.
"""

ITEMS: list[dict] = [
    {
        "symbol": "XAG/USD",
        "name": "Silver",
        "asset_class": "commodity",
        "category": "metal",
        "sector": "",
        "industry": "",
        "exchange": "OTC",
        "country": "",
        "currency": "USD",
        "base": "XAG",
        "aliases": ["xagusd", "silver", "xag", "сребро"],
        "popularity": 10,
        "session": "cme",
        "description": "Среброто — благороден и индустриален метал, по-волатилен от златото; цена за тройунция.",
        "providers": {"twelvedata": "XAG/USD"},
        "price_precision": 3,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 10.0,
        "spread_bps": 3.5,
        "demo": {"anchor_price": 72.0, "daily_vol": 0.025, "daily_volume_usd": 5.0e9, "drift": 0.0002},
    },
    {
        "symbol": "BRENT/USD",
        "name": "Brent Crude Oil",
        "asset_class": "commodity",
        "category": "energy",
        "sector": "",
        "industry": "",
        "exchange": "ICE",
        "country": "",
        "currency": "USD",
        "base": "BRENT",
        "aliases": ["brentusd", "brent", "ukoil", "oil", "crude", "brent oil", "петрол", "нефт", "брент"],
        "popularity": 12,
        "session": "cme",
        "description": "Сортът петрол Brent — основен ориентир за цените на петрола в Европа; цена за барел.",
        "providers": {"twelvedata": "XBR/USD"},
        "price_precision": 2,
        "qty_step": 0.1,
        "min_qty": 0.1,
        "max_leverage": 10.0,
        "spread_bps": 4.0,
        "demo": {"anchor_price": 61.0, "daily_vol": 0.02, "daily_volume_usd": 1.0e10, "drift": 0.0},
    },
    {
        "symbol": "NG/USD",
        "name": "Natural Gas",
        "asset_class": "commodity",
        "category": "energy",
        "sector": "",
        "industry": "",
        "exchange": "CME",
        "country": "",
        "currency": "USD",
        "base": "NG",
        "aliases": ["ngusd", "natgas", "natural gas", "henry hub", "газ", "природен газ"],
        "popularity": 105,
        "session": "cme",
        "description": "Природният газ (Henry Hub) — силно сезонен и волатилен енергиен пазар; цена за MMBtu.",
        "providers": {},
        "price_precision": 3,
        "qty_step": 0.1,
        "min_qty": 0.1,
        "max_leverage": 10.0,
        "spread_bps": 6.0,
        "demo": {"anchor_price": 3.7, "daily_vol": 0.04, "daily_volume_usd": 1.0e10, "drift": 0.0},
    },
    {
        "symbol": "COPPER",
        "name": "Copper",
        "asset_class": "commodity",
        "category": "metal",
        "sector": "",
        "industry": "",
        "exchange": "CME",
        "country": "",
        "currency": "USD",
        "base": "COPPER",
        "aliases": ["copper", "hg", "hg1", "xcu", "мед"],
        "popularity": 110,
        "session": "cme",
        "description": "Медта — индустриален метал, често свързван с икономическата активност; цена за паунд (lb).",
        "providers": {"twelvedata": "HG1"},
        "price_precision": 4,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 10.0,
        "spread_bps": 5.0,
        "demo": {"anchor_price": 5.65, "daily_vol": 0.016, "daily_volume_usd": 6.0e9, "drift": 0.0002},
    },
    {
        "symbol": "XPT/USD",
        "name": "Platinum",
        "asset_class": "commodity",
        "category": "metal",
        "sector": "",
        "industry": "",
        "exchange": "OTC",
        "country": "",
        "currency": "USD",
        "base": "XPT",
        "aliases": ["xptusd", "platinum", "xpt", "платина"],
        "popularity": 115,
        "session": "cme",
        "description": "Платината — рядък метал, използван в автомобилни катализатори и бижута; цена за тройунция.",
        "providers": {"twelvedata": "XPT/USD"},
        "price_precision": 2,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 10.0,
        "spread_bps": 6.0,
        "demo": {"anchor_price": 2050.0, "daily_vol": 0.022, "daily_volume_usd": 1.0e9, "drift": 0.0002},
    },
    {
        "symbol": "XPD/USD",
        "name": "Palladium",
        "asset_class": "commodity",
        "category": "metal",
        "sector": "",
        "industry": "",
        "exchange": "OTC",
        "country": "",
        "currency": "USD",
        "base": "XPD",
        "aliases": ["xpdusd", "palladium", "xpd", "паладий"],
        "popularity": 135,
        "session": "cme",
        "description": "Паладият — метал, търсен главно от автомобилната индустрия; цена за тройунция.",
        "providers": {"twelvedata": "XPD/USD"},
        "price_precision": 2,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 10.0,
        "spread_bps": 8.0,
        "demo": {"anchor_price": 1600.0, "daily_vol": 0.025, "daily_volume_usd": 3.0e8, "drift": 0.0001},
    },
    {
        "symbol": "CORN",
        "name": "Corn",
        "asset_class": "commodity",
        "category": "agriculture",
        "sector": "",
        "industry": "",
        "exchange": "CME",
        "country": "",
        "currency": "USD",
        "base": "CORN",
        "aliases": ["corn", "zc", "царевица"],
        "popularity": 150,
        "session": "cme",
        "description": "Царевицата — една от най-търгуваните селскостопански суровини; цена в USD за бушел.",
        "providers": {},
        "price_precision": 3,
        "qty_step": 0.1,
        "min_qty": 0.1,
        "max_leverage": 10.0,
        "spread_bps": 6.0,
        "demo": {"anchor_price": 4.4, "daily_vol": 0.013, "daily_volume_usd": 3.0e9, "drift": 0.0},
    },
    {
        "symbol": "WHEAT",
        "name": "Wheat",
        "asset_class": "commodity",
        "category": "agriculture",
        "sector": "",
        "industry": "",
        "exchange": "CME",
        "country": "",
        "currency": "USD",
        "base": "WHEAT",
        "aliases": ["wheat", "zw", "пшеница"],
        "popularity": 152,
        "session": "cme",
        "description": "Пшеницата — чувствителна към времето и износа на големите производители; цена в USD за бушел.",
        "providers": {},
        "price_precision": 3,
        "qty_step": 0.1,
        "min_qty": 0.1,
        "max_leverage": 10.0,
        "spread_bps": 7.0,
        "demo": {"anchor_price": 5.1, "daily_vol": 0.016, "daily_volume_usd": 1.5e9, "drift": 0.0},
    },
    {
        "symbol": "SOYBEAN",
        "name": "Soybeans",
        "asset_class": "commodity",
        "category": "agriculture",
        "sector": "",
        "industry": "",
        "exchange": "CME",
        "country": "",
        "currency": "USD",
        "base": "SOYBEAN",
        "aliases": ["soybean", "soybeans", "soy", "zs", "соя"],
        "popularity": 155,
        "session": "cme",
        "description": "Соята — ключова суровина за фуражи и растителни масла; цена в USD за бушел.",
        "providers": {},
        "price_precision": 3,
        "qty_step": 0.1,
        "min_qty": 0.1,
        "max_leverage": 10.0,
        "spread_bps": 6.0,
        "demo": {"anchor_price": 10.5, "daily_vol": 0.011, "daily_volume_usd": 3.0e9, "drift": 0.0},
    },
    {
        "symbol": "COFFEE",
        "name": "Coffee (Arabica)",
        "asset_class": "commodity",
        "category": "agriculture",
        "sector": "",
        "industry": "",
        "exchange": "ICE",
        "country": "",
        "currency": "USD",
        "base": "COFFEE",
        "aliases": ["coffee", "arabica", "kc", "кафе"],
        "popularity": 157,
        "session": "cme",
        "description": "Кафето Арабика — пазар, силно зависим от реколтата в Бразилия; цена в USD за паунд (lb).",
        "providers": {},
        "price_precision": 4,
        "qty_step": 0.1,
        "min_qty": 0.1,
        "max_leverage": 10.0,
        "spread_bps": 8.0,
        "demo": {"anchor_price": 3.5, "daily_vol": 0.025, "daily_volume_usd": 1.0e9, "drift": 0.0},
    },
    {
        "symbol": "COCOA",
        "name": "Cocoa",
        "asset_class": "commodity",
        "category": "agriculture",
        "sector": "",
        "industry": "",
        "exchange": "ICE",
        "country": "",
        "currency": "USD",
        "base": "COCOA",
        "aliases": ["cocoa", "cc", "какао"],
        "popularity": 160,
        "session": "cme",
        "description": "Какаото — производството е съсредоточено в Западна Африка, а цената може да се движи рязко; цена в USD за тон.",
        "providers": {},
        "price_precision": 2,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 10.0,
        "spread_bps": 10.0,
        "demo": {"anchor_price": 6000.0, "daily_vol": 0.035, "daily_volume_usd": 5.0e8, "drift": 0.0},
    },
    {
        "symbol": "SUGAR",
        "name": "Sugar No.11",
        "asset_class": "commodity",
        "category": "agriculture",
        "sector": "",
        "industry": "",
        "exchange": "ICE",
        "country": "",
        "currency": "USD",
        "base": "SUGAR",
        "aliases": ["sugar", "sb", "захар"],
        "popularity": 165,
        "session": "cme",
        "description": "Суровата захар (No.11) зависи от реколтата и от производството на етанол в Бразилия; цена в USD за паунд (lb).",
        "providers": {},
        "price_precision": 4,
        "qty_step": 0.1,
        "min_qty": 0.1,
        "max_leverage": 10.0,
        "spread_bps": 10.0,
        "demo": {"anchor_price": 0.149, "daily_vol": 0.018, "daily_volume_usd": 5.0e8, "drift": 0.0},
    },
    {
        "symbol": "COTTON",
        "name": "Cotton No.2",
        "asset_class": "commodity",
        "category": "agriculture",
        "sector": "",
        "industry": "",
        "exchange": "ICE",
        "country": "",
        "currency": "USD",
        "base": "COTTON",
        "aliases": ["cotton", "ct", "памук"],
        "popularity": 170,
        "session": "cme",
        "description": "Памукът — суровина за текстилната индустрия, чувствителна към времето и търговията; цена в USD за паунд (lb).",
        "providers": {},
        "price_precision": 4,
        "qty_step": 0.1,
        "min_qty": 0.1,
        "max_leverage": 10.0,
        "spread_bps": 10.0,
        "demo": {"anchor_price": 0.64, "daily_vol": 0.013, "daily_volume_usd": 3.0e8, "drift": 0.0},
    },
]

EXISTING_METADATA: dict[str, dict] = {
    "XAU/USD": {
        "category": "metal",
        "sector": "",
        "industry": "",
        "exchange": "OTC",
        "country": "",
        "currency": "USD",
        "base": "XAU",
        "aliases": ["xauusd", "gold", "xau", "злато"],
        "popularity": 4,
        "session": "cme",
    },
    "WTI/USD": {
        "category": "energy",
        "sector": "",
        "industry": "",
        "exchange": "CME",
        "country": "",
        "currency": "USD",
        "base": "WTI",
        "aliases": ["wtiusd", "wti", "oil", "crude", "crude oil", "usoil", "петрол", "нефт"],
        "popularity": 8,
        "session": "cme",
    },
}
