"""Crypto instruments (Binance spot pairs plus a few Twelve Data USD-quoted markets).

Reference data only: plain dict literals, no imports from the app.
* Binance symbols were checked against /api/v3/exchangeInfo (status TRADING); price_precision, qty_step and
  min_qty come from the PRICE_FILTER tickSize and LOT_SIZE stepSize/minQty filters.
* Twelve Data symbols were checked against /cryptocurrencies (including the coin name, because Twelve Data
  reuses some tickers for unrelated coins - e.g. DOT/USD, OP/USD, IMX/USD and STX/USD are other projects there,
  so those mappings are intentionally omitted).
* `demo` only parameterises the clearly-labelled SYNTHETIC demo generator. anchor_price is the approximate
  Binance price on 2026-01-01; daily_vol / daily_volume_usd are rough orders of magnitude, not real statistics.
"""

ITEMS: list[dict] = [
    {
        "symbol": "BNB/USDT",
        "name": "BNB",
        "asset_class": "crypto",
        "category": "exchange",
        "sector": "Exchange token",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "BNB",
        "aliases": ["bnbusdt", "bnb", "binance coin", "бинанс"],
        "popularity": 11,
        "session": "24x7",
        "description": "Токенът на екосистемата Binance и BNB Chain; използва се и за плащане на такси в мрежата.",
        "providers": {"binance": "BNBUSDT", "twelvedata": "BNB/USD"},
        "price_precision": 2,
        "qty_step": 0.001,
        "min_qty": 0.001,
        "max_leverage": 2.0,
        "spread_bps": 2.0,
        "demo": {"anchor_price": 864.3, "daily_vol": 0.03, "daily_volume_usd": 1.0e9, "drift": 0.0004},
    },
    {
        "symbol": "DOGE/USDT",
        "name": "Dogecoin",
        "asset_class": "crypto",
        "category": "meme",
        "sector": "Meme coin",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "DOGE",
        "aliases": ["dogeusdt", "doge", "dogecoin", "догекойн"],
        "popularity": 13,
        "session": "24x7",
        "description": "Първата голяма meme криптовалута — цената често реагира на социалните мрежи.",
        "providers": {"binance": "DOGEUSDT", "twelvedata": "DOGE/USD"},
        "price_precision": 5,
        "qty_step": 1.0,
        "min_qty": 1.0,
        "max_leverage": 2.0,
        "spread_bps": 6.0,
        "demo": {"anchor_price": 0.1175, "daily_vol": 0.047, "daily_volume_usd": 7.0e8, "drift": 0.0002},
    },
    {
        "symbol": "ADA/USDT",
        "name": "Cardano",
        "asset_class": "crypto",
        "category": "layer1",
        "sector": "Smart contract platform",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "ADA",
        "aliases": ["adausdt", "ada", "cardano", "кардано"],
        "popularity": 16,
        "session": "24x7",
        "description": "Proof-of-stake блокчейн платформа за smart contracts.",
        "providers": {"binance": "ADAUSDT", "twelvedata": "ADA/USD"},
        "price_precision": 4,
        "qty_step": 0.1,
        "min_qty": 0.1,
        "max_leverage": 2.0,
        "spread_bps": 4.0,
        "demo": {"anchor_price": 0.3336, "daily_vol": 0.043, "daily_volume_usd": 3.0e8, "drift": 0.0004},
    },
    {
        "symbol": "LINK/USDT",
        "name": "Chainlink",
        "asset_class": "crypto",
        "category": "infrastructure",
        "sector": "Oracle network",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "LINK",
        "aliases": ["linkusdt", "link", "chainlink", "чейнлинк"],
        "popularity": 20,
        "session": "24x7",
        "description": "Oracle мрежа, която доставя външни данни (например цени) към smart contracts.",
        "providers": {"binance": "LINKUSDT", "twelvedata": "LINK/USD"},
        "price_precision": 3,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 2.0,
        "spread_bps": 4.0,
        "demo": {"anchor_price": 12.2, "daily_vol": 0.047, "daily_volume_usd": 3.0e8, "drift": 0.0004},
    },
    {
        "symbol": "AVAX/USDT",
        "name": "Avalanche",
        "asset_class": "crypto",
        "category": "layer1",
        "sector": "Smart contract platform",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "AVAX",
        "aliases": ["avaxusdt", "avax", "avalanche", "аваланш"],
        "popularity": 22,
        "session": "24x7",
        "description": "Layer 1 блокчейн с бърза финализация на транзакциите и собствени подмрежи.",
        "providers": {"binance": "AVAXUSDT", "twelvedata": "AVAX/USD"},
        "price_precision": 3,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 2.0,
        "spread_bps": 4.0,
        "demo": {"anchor_price": 12.32, "daily_vol": 0.048, "daily_volume_usd": 2.0e8, "drift": 0.0004},
    },
    {
        "symbol": "TRX/USDT",
        "name": "TRON",
        "asset_class": "crypto",
        "category": "layer1",
        "sector": "Smart contract platform",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "TRX",
        "aliases": ["trxusdt", "trx", "tron", "трон"],
        "popularity": 24,
        "session": "24x7",
        "description": "Блокчейн, широко използван за трансфери на stablecoins като USDT.",
        "providers": {"binance": "TRXUSDT", "twelvedata": "TRX/USD"},
        "price_precision": 4,
        "qty_step": 0.1,
        "min_qty": 0.1,
        "max_leverage": 2.0,
        "spread_bps": 4.0,
        "demo": {"anchor_price": 0.2846, "daily_vol": 0.02, "daily_volume_usd": 4.0e8, "drift": 0.0004},
    },
    {
        "symbol": "SUI/USDT",
        "name": "Sui",
        "asset_class": "crypto",
        "category": "layer1",
        "sector": "Smart contract platform",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "SUI",
        "aliases": ["suiusdt", "sui", "суи"],
        "popularity": 26,
        "session": "24x7",
        "description": "Високопроизводителен layer 1 блокчейн, базиран на езика Move.",
        "providers": {"binance": "SUIUSDT", "twelvedata": "SUI/USD"},
        "price_precision": 4,
        "qty_step": 0.1,
        "min_qty": 0.1,
        "max_leverage": 2.0,
        "spread_bps": 4.0,
        "demo": {"anchor_price": 1.404, "daily_vol": 0.05, "daily_volume_usd": 4.0e8, "drift": 0.0004},
    },
    {
        "symbol": "LTC/USDT",
        "name": "Litecoin",
        "asset_class": "crypto",
        "category": "payments",
        "sector": "Payments",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "LTC",
        "aliases": ["ltcusdt", "ltc", "litecoin", "лайткойн"],
        "popularity": 28,
        "session": "24x7",
        "description": "Една от най-старите криптовалути, създадена като по-бърза алтернатива за плащания.",
        "providers": {"binance": "LTCUSDT", "twelvedata": "LTC/USD"},
        "price_precision": 2,
        "qty_step": 0.001,
        "min_qty": 0.001,
        "max_leverage": 2.0,
        "spread_bps": 4.0,
        "demo": {"anchor_price": 76.86, "daily_vol": 0.04, "daily_volume_usd": 2.0e8, "drift": 0.0004},
    },
    {
        "symbol": "BCH/USDT",
        "name": "Bitcoin Cash",
        "asset_class": "crypto",
        "category": "payments",
        "sector": "Payments",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "BCH",
        "aliases": ["bchusdt", "bch", "bitcoin cash", "биткойн кеш"],
        "popularity": 30,
        "session": "24x7",
        "description": "Разклонение (fork) на Bitcoin от 2017 г. с по-големи блокове.",
        "providers": {"binance": "BCHUSDT", "twelvedata": "BCH/USD"},
        "price_precision": 1,
        "qty_step": 0.001,
        "min_qty": 0.001,
        "max_leverage": 2.0,
        "spread_bps": 5.0,
        "demo": {"anchor_price": 599.6, "daily_vol": 0.036, "daily_volume_usd": 1.0e8, "drift": 0.0004},
    },
    {
        "symbol": "XLM/USDT",
        "name": "Stellar",
        "asset_class": "crypto",
        "category": "payments",
        "sector": "Payments",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "XLM",
        "aliases": ["xlmusdt", "xlm", "stellar", "lumens", "стелар"],
        "popularity": 32,
        "session": "24x7",
        "description": "Мрежа за евтини международни плащания и токенизирани активи.",
        "providers": {"binance": "XLMUSDT", "twelvedata": "XLM/USD"},
        "price_precision": 4,
        "qty_step": 1.0,
        "min_qty": 1.0,
        "max_leverage": 2.0,
        "spread_bps": 5.0,
        "demo": {"anchor_price": 0.201, "daily_vol": 0.043, "daily_volume_usd": 7.0e7, "drift": 0.0004},
    },
    {
        "symbol": "SHIB/USDT",
        "name": "Shiba Inu",
        "asset_class": "crypto",
        "category": "meme",
        "sector": "Meme coin",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "SHIB",
        "aliases": ["shibusdt", "shib", "shiba", "shiba inu", "шиба ину"],
        "popularity": 34,
        "session": "24x7",
        "description": "Meme токен с много ниска цена на единица — обърни внимание на броя единици в позицията.",
        "providers": {"binance": "SHIBUSDT", "twelvedata": "SHIB/USD"},
        "price_precision": 8,
        "qty_step": 1.0,
        "min_qty": 1.0,
        "max_leverage": 2.0,
        "spread_bps": 12.0,
        "demo": {"anchor_price": 0.00000691, "daily_vol": 0.037, "daily_volume_usd": 5.0e7, "drift": 0.0002},
    },
    {
        "symbol": "PEPE/USDT",
        "name": "Pepe",
        "asset_class": "crypto",
        "category": "meme",
        "sector": "Meme coin",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "PEPE",
        "aliases": ["pepeusdt", "pepe", "пепе"],
        "popularity": 36,
        "session": "24x7",
        "description": "Meme токен с изключително ниска цена на единица и висока волатилност.",
        "providers": {"binance": "PEPEUSDT", "twelvedata": "PEPE/USD"},
        "price_precision": 8,
        "qty_step": 1.0,
        "min_qty": 1.0,
        "max_leverage": 2.0,
        "spread_bps": 10.0,
        "demo": {"anchor_price": 0.00000404, "daily_vol": 0.054, "daily_volume_usd": 2.0e8, "drift": 0.0002},
    },
    {
        "symbol": "DOT/USDT",
        "name": "Polkadot",
        "asset_class": "crypto",
        "category": "layer1",
        "sector": "Interoperability",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "DOT",
        "aliases": ["dotusdt", "dot", "polkadot", "полкадот"],
        "popularity": 38,
        "session": "24x7",
        "description": "Мрежа, която свързва отделни блокчейни (parachains) в обща система.",
        "providers": {"binance": "DOTUSDT"},
        "price_precision": 3,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 2.0,
        "spread_bps": 5.0,
        "demo": {"anchor_price": 1.789, "daily_vol": 0.048, "daily_volume_usd": 9.0e7, "drift": 0.0004},
    },
    {
        "symbol": "HBAR/USDT",
        "name": "Hedera",
        "asset_class": "crypto",
        "category": "layer1",
        "sector": "Smart contract platform",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "HBAR",
        "aliases": ["hbarusdt", "hbar", "hedera", "hedera hashgraph", "хедера"],
        "popularity": 40,
        "session": "24x7",
        "description": "Публична мрежа с hashgraph консенсус, управлявана от съвет от компании.",
        "providers": {"binance": "HBARUSDT", "twelvedata": "HBAR/USD"},
        "price_precision": 5,
        "qty_step": 1.0,
        "min_qty": 1.0,
        "max_leverage": 2.0,
        "spread_bps": 5.0,
        "demo": {"anchor_price": 0.1063, "daily_vol": 0.049, "daily_volume_usd": 1.0e8, "drift": 0.0004},
    },
    {
        "symbol": "HYPE/USDT",
        "name": "Hyperliquid",
        "asset_class": "crypto",
        "category": "exchange",
        "sector": "Decentralized derivatives exchange",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "HYPE",
        "aliases": ["hypeusdt", "hype", "hyperliquid", "хиперликуид"],
        "popularity": 42,
        "session": "24x7",
        "description": "Токенът на Hyperliquid — децентрализирана борса за perpetual фючърси със собствен блокчейн.",
        "providers": {"binance": "HYPEUSDT", "twelvedata": "HYPE/USDT"},
        "price_precision": 2,
        "qty_step": 0.001,
        "min_qty": 0.001,
        "max_leverage": 2.0,
        "spread_bps": 4.0,
        "demo": {"anchor_price": 25.5, "daily_vol": 0.06, "daily_volume_usd": 3.0e8, "drift": 0.0004},
    },
    {
        "symbol": "UNI/USDT",
        "name": "Uniswap",
        "asset_class": "crypto",
        "category": "defi",
        "sector": "Decentralized exchange",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "UNI",
        "aliases": ["uniusdt", "uni", "uniswap", "юнисуап"],
        "popularity": 48,
        "session": "24x7",
        "description": "Governance токен на Uniswap — една от най-известните децентрализирани борси (DEX).",
        "providers": {"binance": "UNIUSDT", "twelvedata": "UNI/USD"},
        "price_precision": 3,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 2.0,
        "spread_bps": 5.0,
        "demo": {"anchor_price": 5.641, "daily_vol": 0.057, "daily_volume_usd": 1.0e8, "drift": 0.0004},
    },
    {
        "symbol": "AAVE/USDT",
        "name": "Aave",
        "asset_class": "crypto",
        "category": "defi",
        "sector": "Lending",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "AAVE",
        "aliases": ["aaveusdt", "aave", "ааве"],
        "popularity": 50,
        "session": "24x7",
        "description": "Протокол за децентрализирано отпускане и вземане на заеми в криптоактиви.",
        "providers": {"binance": "AAVEUSDT", "twelvedata": "AAVE/USD"},
        "price_precision": 2,
        "qty_step": 0.001,
        "min_qty": 0.001,
        "max_leverage": 2.0,
        "spread_bps": 5.0,
        "demo": {"anchor_price": 146.0, "daily_vol": 0.046, "daily_volume_usd": 1.0e8, "drift": 0.0004},
    },
    {
        "symbol": "NEAR/USDT",
        "name": "NEAR Protocol",
        "asset_class": "crypto",
        "category": "layer1",
        "sector": "Smart contract platform",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "NEAR",
        "aliases": ["nearusdt", "near", "near protocol", "ниър"],
        "popularity": 52,
        "session": "24x7",
        "description": "Layer 1 блокчейн с фокус върху лесна употреба и AI приложения.",
        "providers": {"binance": "NEARUSDT", "twelvedata": "NEAR/USD"},
        "price_precision": 3,
        "qty_step": 0.1,
        "min_qty": 0.1,
        "max_leverage": 2.0,
        "spread_bps": 5.0,
        "demo": {"anchor_price": 1.514, "daily_vol": 0.051, "daily_volume_usd": 1.0e8, "drift": 0.0004},
    },
    {
        "symbol": "TRUMP/USDT",
        "name": "Official Trump",
        "asset_class": "crypto",
        "category": "meme",
        "sector": "Meme coin",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "TRUMP",
        "aliases": ["trumpusdt", "trump", "official trump", "тръмп"],
        "popularity": 54,
        "session": "24x7",
        "description": "Meme токен, стартиран през януари 2025 г. — пример за силно спекулативен актив.",
        "providers": {"binance": "TRUMPUSDT", "twelvedata": "TRUMP/USDT"},
        "price_precision": 3,
        "qty_step": 0.001,
        "min_qty": 0.001,
        "max_leverage": 2.0,
        "spread_bps": 12.0,
        "demo": {"anchor_price": 4.802, "daily_vol": 0.046, "daily_volume_usd": 9.0e7, "drift": 0.0002},
    },
    {
        "symbol": "ZEC/USDT",
        "name": "Zcash",
        "asset_class": "crypto",
        "category": "other",
        "sector": "Privacy",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "ZEC",
        "aliases": ["zecusdt", "zec", "zcash", "зикеш"],
        "popularity": 56,
        "session": "24x7",
        "description": "Криптовалута с опция за поверителни (shielded) транзакции.",
        "providers": {"binance": "ZECUSDT", "twelvedata": "ZEC/USD"},
        "price_precision": 2,
        "qty_step": 0.001,
        "min_qty": 0.001,
        "max_leverage": 2.0,
        "spread_bps": 3.0,
        "demo": {"anchor_price": 512.4, "daily_vol": 0.086, "daily_volume_usd": 1.0e9, "drift": 0.0004},
    },
    {
        "symbol": "TAO/USDT",
        "name": "Bittensor",
        "asset_class": "crypto",
        "category": "ai",
        "sector": "Decentralized AI",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "TAO",
        "aliases": ["taousdt", "tao", "bittensor", "битенсор"],
        "popularity": 58,
        "session": "24x7",
        "description": "Децентрализирана мрежа, в която участниците обучават и предоставят AI модели.",
        "providers": {"binance": "TAOUSDT", "twelvedata": "TAO/USD"},
        "price_precision": 1,
        "qty_step": 0.0001,
        "min_qty": 0.0001,
        "max_leverage": 2.0,
        "spread_bps": 4.0,
        "demo": {"anchor_price": 219.2, "daily_vol": 0.051, "daily_volume_usd": 2.0e8, "drift": 0.0004},
    },
    {
        "symbol": "APT/USDT",
        "name": "Aptos",
        "asset_class": "crypto",
        "category": "layer1",
        "sector": "Smart contract platform",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "APT",
        "aliases": ["aptusdt", "apt", "aptos", "аптос"],
        "popularity": 106,
        "session": "24x7",
        "description": "Layer 1 блокчейн, базиран на езика Move.",
        "providers": {"binance": "APTUSDT", "twelvedata": "APT/USD"},
        "price_precision": 4,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 2.0,
        "spread_bps": 5.0,
        "demo": {"anchor_price": 1.659, "daily_vol": 0.049, "daily_volume_usd": 8.0e7, "drift": 0.0003},
    },
    {
        "symbol": "ICP/USDT",
        "name": "Internet Computer",
        "asset_class": "crypto",
        "category": "layer1",
        "sector": "Smart contract platform",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "ICP",
        "aliases": ["icpusdt", "icp", "internet computer", "dfinity"],
        "popularity": 108,
        "session": "24x7",
        "description": "Блокчейн платформа за хостване на приложения изцяло on-chain.",
        "providers": {"binance": "ICPUSDT", "twelvedata": "ICP/USD"},
        "price_precision": 3,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 2.0,
        "spread_bps": 5.0,
        "demo": {"anchor_price": 2.841, "daily_vol": 0.064, "daily_volume_usd": 7.0e7, "drift": 0.0003},
    },
    {
        "symbol": "ETC/USDT",
        "name": "Ethereum Classic",
        "asset_class": "crypto",
        "category": "layer1",
        "sector": "Smart contract platform",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "ETC",
        "aliases": ["etcusdt", "etc", "ethereum classic", "етериум класик"],
        "popularity": 110,
        "session": "24x7",
        "description": "Оригиналната верига на Ethereum, запазена след разделението през 2016 г.",
        "providers": {"binance": "ETCUSDT", "twelvedata": "ETC/USD"},
        "price_precision": 2,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 2.0,
        "spread_bps": 7.0,
        "demo": {"anchor_price": 11.47, "daily_vol": 0.045, "daily_volume_usd": 4.0e7, "drift": 0.0003},
    },
    {
        "symbol": "ENA/USDT",
        "name": "Ethena",
        "asset_class": "crypto",
        "category": "defi",
        "sector": "Synthetic dollar",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "ENA",
        "aliases": ["enausdt", "ena", "ethena", "usde"],
        "popularity": 112,
        "session": "24x7",
        "description": "Governance токен на Ethena — протоколът зад синтетичния долар USDe.",
        "providers": {"binance": "ENAUSDT", "twelvedata": "ENA/USD"},
        "price_precision": 4,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 2.0,
        "spread_bps": 4.0,
        "demo": {"anchor_price": 0.2, "daily_vol": 0.064, "daily_volume_usd": 2.0e8, "drift": 0.0003},
    },
    {
        "symbol": "ONDO/USDT",
        "name": "Ondo",
        "asset_class": "crypto",
        "category": "defi",
        "sector": "Real-world assets",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "ONDO",
        "aliases": ["ondousdt", "ondo", "ondo finance", "rwa"],
        "popularity": 114,
        "session": "24x7",
        "description": "Проект за токенизиране на реални активи като държавни облигации (RWA).",
        "providers": {"binance": "ONDOUSDT", "twelvedata": "ONDO/USD"},
        "price_precision": 4,
        "qty_step": 0.1,
        "min_qty": 0.1,
        "max_leverage": 2.0,
        "spread_bps": 7.0,
        "demo": {"anchor_price": 0.3592, "daily_vol": 0.045, "daily_volume_usd": 4.0e7, "drift": 0.0003},
    },
    {
        "symbol": "POL/USDT",
        "name": "Polygon",
        "asset_class": "crypto",
        "category": "layer2",
        "sector": "Ethereum scaling",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "POL",
        "aliases": ["polusdt", "pol", "polygon", "matic", "полигон"],
        "popularity": 116,
        "session": "24x7",
        "description": "Токенът на Polygon (бивш MATIC) — мрежа за мащабиране на Ethereum.",
        "providers": {"binance": "POLUSDT", "twelvedata": "POL/USD"},
        "price_precision": 5,
        "qty_step": 0.1,
        "min_qty": 0.1,
        "max_leverage": 2.0,
        "spread_bps": 7.0,
        "demo": {"anchor_price": 0.1006, "daily_vol": 0.042, "daily_volume_usd": 4.0e7, "drift": 0.0003},
    },
    {
        "symbol": "ARB/USDT",
        "name": "Arbitrum",
        "asset_class": "crypto",
        "category": "layer2",
        "sector": "Ethereum rollup",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "ARB",
        "aliases": ["arbusdt", "arb", "arbitrum", "арбитрум"],
        "popularity": 118,
        "session": "24x7",
        "description": "Governance токен на Arbitrum — layer 2 мрежа върху Ethereum.",
        "providers": {"binance": "ARBUSDT", "twelvedata": "ARB/USD"},
        "price_precision": 4,
        "qty_step": 0.1,
        "min_qty": 0.1,
        "max_leverage": 2.0,
        "spread_bps": 5.0,
        "demo": {"anchor_price": 0.1869, "daily_vol": 0.057, "daily_volume_usd": 9.0e7, "drift": 0.0003},
    },
    {
        "symbol": "FET/USDT",
        "name": "Fetch.ai (ASI Alliance)",
        "asset_class": "crypto",
        "category": "ai",
        "sector": "AI agents",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "FET",
        "aliases": ["fetusdt", "fet", "fetch", "fetch.ai", "asi", "artificial superintelligence alliance"],
        "popularity": 120,
        "session": "24x7",
        "description": "Токенът на Artificial Superintelligence Alliance (Fetch.ai) — проекти за автономни AI агенти.",
        "providers": {"binance": "FETUSDT", "twelvedata": "FET/USD"},
        "price_precision": 4,
        "qty_step": 0.1,
        "min_qty": 0.1,
        "max_leverage": 2.0,
        "spread_bps": 5.0,
        "demo": {"anchor_price": 0.1987, "daily_vol": 0.064, "daily_volume_usd": 9.0e7, "drift": 0.0003},
    },
    {
        "symbol": "RENDER/USDT",
        "name": "Render",
        "asset_class": "crypto",
        "category": "ai",
        "sector": "GPU computing",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "RENDER",
        "aliases": ["renderusdt", "render", "rndr", "render network"],
        "popularity": 122,
        "session": "24x7",
        "description": "Децентрализирана мрежа за GPU изчисления — рендиране на графика и AI задачи.",
        "providers": {"binance": "RENDERUSDT", "twelvedata": "RENDER/USD"},
        "price_precision": 3,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 2.0,
        "spread_bps": 7.0,
        "demo": {"anchor_price": 1.287, "daily_vol": 0.055, "daily_volume_usd": 3.0e7, "drift": 0.0003},
    },
    {
        "symbol": "WLD/USDT",
        "name": "Worldcoin",
        "asset_class": "crypto",
        "category": "ai",
        "sector": "Digital identity",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "WLD",
        "aliases": ["wldusdt", "wld", "worldcoin", "world", "уърлдкойн"],
        "popularity": 124,
        "session": "24x7",
        "description": "Проект за дигитална идентичност (World ID), свързан с AI тематиката.",
        "providers": {"binance": "WLDUSDT", "twelvedata": "WLD/USD"},
        "price_precision": 4,
        "qty_step": 0.1,
        "min_qty": 0.1,
        "max_leverage": 2.0,
        "spread_bps": 5.0,
        "demo": {"anchor_price": 0.4807, "daily_vol": 0.066, "daily_volume_usd": 1.0e8, "drift": 0.0003},
    },
    {
        "symbol": "BONK/USDT",
        "name": "Bonk",
        "asset_class": "crypto",
        "category": "meme",
        "sector": "Meme coin",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "BONK",
        "aliases": ["bonkusdt", "bonk", "бонк"],
        "popularity": 126,
        "session": "24x7",
        "description": "Meme токен от екосистемата на Solana с много ниска цена на единица.",
        "providers": {"binance": "BONKUSDT", "twelvedata": "BONK/USDT"},
        "price_precision": 8,
        "qty_step": 1.0,
        "min_qty": 1.0,
        "max_leverage": 2.0,
        "spread_bps": 12.0,
        "demo": {"anchor_price": 0.00000747, "daily_vol": 0.064, "daily_volume_usd": 8.0e7, "drift": 0.0002},
    },
    {
        "symbol": "WIF/USDT",
        "name": "dogwifhat",
        "asset_class": "crypto",
        "category": "meme",
        "sector": "Meme coin",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "WIF",
        "aliases": ["wifusdt", "wif", "dogwifhat"],
        "popularity": 128,
        "session": "24x7",
        "description": "Meme токен от екосистемата на Solana — силно волатилен.",
        "providers": {"binance": "WIFUSDT", "twelvedata": "WIF/USDT"},
        "price_precision": 4,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 2.0,
        "spread_bps": 12.0,
        "demo": {"anchor_price": 0.271, "daily_vol": 0.065, "daily_volume_usd": 9.0e7, "drift": 0.0002},
    },
    {
        "symbol": "FLOKI/USDT",
        "name": "Floki",
        "asset_class": "crypto",
        "category": "meme",
        "sector": "Meme coin",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "FLOKI",
        "aliases": ["flokiusdt", "floki", "флоки"],
        "popularity": 130,
        "session": "24x7",
        "description": "Meme токен, вдъхновен от куче на име Floki.",
        "providers": {"binance": "FLOKIUSDT", "twelvedata": "FLOKI/USDT"},
        "price_precision": 8,
        "qty_step": 1.0,
        "min_qty": 1.0,
        "max_leverage": 2.0,
        "spread_bps": 15.0,
        "demo": {"anchor_price": 0.00003943, "daily_vol": 0.06, "daily_volume_usd": 4.0e7, "drift": 0.0002},
    },
    {
        "symbol": "PENGU/USDT",
        "name": "Pudgy Penguins",
        "asset_class": "crypto",
        "category": "meme",
        "sector": "Meme coin",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "PENGU",
        "aliases": ["penguusdt", "pengu", "pudgy penguins", "пингвин"],
        "popularity": 132,
        "session": "24x7",
        "description": "Токенът на NFT колекцията Pudgy Penguins.",
        "providers": {"binance": "PENGUUSDT", "twelvedata": "PENGU/USDT"},
        "price_precision": 6,
        "qty_step": 1.0,
        "min_qty": 1.0,
        "max_leverage": 2.0,
        "spread_bps": 12.0,
        "demo": {"anchor_price": 0.008677, "daily_vol": 0.07, "daily_volume_usd": 1.0e8, "drift": 0.0002},
    },
    {
        "symbol": "ATOM/USDT",
        "name": "Cosmos",
        "asset_class": "crypto",
        "category": "layer1",
        "sector": "Interoperability",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "ATOM",
        "aliases": ["atomusdt", "atom", "cosmos", "космос"],
        "popularity": 134,
        "session": "24x7",
        "description": "Екосистема от свързани блокчейни, изградени с Cosmos SDK.",
        "providers": {"binance": "ATOMUSDT", "twelvedata": "ATOM/USD"},
        "price_precision": 3,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 2.0,
        "spread_bps": 7.0,
        "demo": {"anchor_price": 1.93, "daily_vol": 0.043, "daily_volume_usd": 2.0e7, "drift": 0.0003},
    },
    {
        "symbol": "FIL/USDT",
        "name": "Filecoin",
        "asset_class": "crypto",
        "category": "infrastructure",
        "sector": "Decentralized storage",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "FIL",
        "aliases": ["filusdt", "fil", "filecoin", "файлкойн"],
        "popularity": 136,
        "session": "24x7",
        "description": "Децентрализирана мрежа за съхранение на файлове.",
        "providers": {"binance": "FILUSDT", "twelvedata": "FIL/USD"},
        "price_precision": 4,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 2.0,
        "spread_bps": 5.0,
        "demo": {"anchor_price": 1.298, "daily_vol": 0.069, "daily_volume_usd": 8.0e7, "drift": 0.0003},
    },
    {
        "symbol": "OP/USDT",
        "name": "Optimism",
        "asset_class": "crypto",
        "category": "layer2",
        "sector": "Ethereum rollup",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "OP",
        "aliases": ["opusdt", "op", "optimism", "оптимизъм"],
        "popularity": 138,
        "session": "24x7",
        "description": "Governance токен на Optimism — layer 2 мрежа върху Ethereum.",
        "providers": {"binance": "OPUSDT"},
        "price_precision": 4,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 2.0,
        "spread_bps": 7.0,
        "demo": {"anchor_price": 0.2679, "daily_vol": 0.056, "daily_volume_usd": 4.0e7, "drift": 0.0003},
    },
    {
        "symbol": "INJ/USDT",
        "name": "Injective",
        "asset_class": "crypto",
        "category": "defi",
        "sector": "Derivatives",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "INJ",
        "aliases": ["injusdt", "inj", "injective"],
        "popularity": 140,
        "session": "24x7",
        "description": "Блокчейн, специализиран за финансови и деривативни приложения.",
        "providers": {"binance": "INJUSDT", "twelvedata": "INJ/USD"},
        "price_precision": 3,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 2.0,
        "spread_bps": 7.0,
        "demo": {"anchor_price": 4.19, "daily_vol": 0.056, "daily_volume_usd": 3.0e7, "drift": 0.0003},
    },
    {
        "symbol": "SEI/USDT",
        "name": "Sei",
        "asset_class": "crypto",
        "category": "layer1",
        "sector": "Smart contract platform",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "SEI",
        "aliases": ["seiusdt", "sei"],
        "popularity": 142,
        "session": "24x7",
        "description": "Layer 1 блокчейн, оптимизиран за търговски приложения.",
        "providers": {"binance": "SEIUSDT", "twelvedata": "SEI/USD"},
        "price_precision": 5,
        "qty_step": 0.1,
        "min_qty": 0.1,
        "max_leverage": 2.0,
        "spread_bps": 5.0,
        "demo": {"anchor_price": 0.111, "daily_vol": 0.051, "daily_volume_usd": 7.0e7, "drift": 0.0003},
    },
    {
        "symbol": "TIA/USDT",
        "name": "Celestia",
        "asset_class": "crypto",
        "category": "infrastructure",
        "sector": "Data availability",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "TIA",
        "aliases": ["tiausdt", "tia", "celestia", "селестия"],
        "popularity": 144,
        "session": "24x7",
        "description": "Модулен блокчейн, който осигурява наличност на данни (data availability) за други вериги.",
        "providers": {"binance": "TIAUSDT", "twelvedata": "TIA/USD"},
        "price_precision": 4,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 2.0,
        "spread_bps": 7.0,
        "demo": {"anchor_price": 0.4558, "daily_vol": 0.063, "daily_volume_usd": 5.0e7, "drift": 0.0003},
    },
    {
        "symbol": "ALGO/USDT",
        "name": "Algorand",
        "asset_class": "crypto",
        "category": "layer1",
        "sector": "Smart contract platform",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "ALGO",
        "aliases": ["algousdt", "algo", "algorand", "алгоранд"],
        "popularity": 146,
        "session": "24x7",
        "description": "Proof-of-stake блокчейн с акцент върху бързи и евтини транзакции.",
        "providers": {"binance": "ALGOUSDT", "twelvedata": "ALGO/USD"},
        "price_precision": 4,
        "qty_step": 1.0,
        "min_qty": 1.0,
        "max_leverage": 2.0,
        "spread_bps": 7.0,
        "demo": {"anchor_price": 0.1105, "daily_vol": 0.046, "daily_volume_usd": 2.0e7, "drift": 0.0003},
    },
    {
        "symbol": "VET/USDT",
        "name": "VeChain",
        "asset_class": "crypto",
        "category": "layer1",
        "sector": "Supply chain",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "VET",
        "aliases": ["vetusdt", "vet", "vechain", "вечейн"],
        "popularity": 148,
        "session": "24x7",
        "description": "Блокчейн, ориентиран към проследяване на вериги за доставки.",
        "providers": {"binance": "VETUSDT", "twelvedata": "VET/USD"},
        "price_precision": 6,
        "qty_step": 0.1,
        "min_qty": 0.1,
        "max_leverage": 2.0,
        "spread_bps": 7.0,
        "demo": {"anchor_price": 0.01043, "daily_vol": 0.045, "daily_volume_usd": 2.0e7, "drift": 0.0003},
    },
    {
        "symbol": "VIRTUAL/USDT",
        "name": "Virtuals Protocol",
        "asset_class": "crypto",
        "category": "ai",
        "sector": "AI agents",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "VIRTUAL",
        "aliases": ["virtualusdt", "virtual", "virtuals", "virtuals protocol"],
        "popularity": 150,
        "session": "24x7",
        "description": "Платформа за създаване на AI агенти, токенизирани on-chain.",
        "providers": {"binance": "VIRTUALUSDT"},
        "price_precision": 4,
        "qty_step": 0.1,
        "min_qty": 0.1,
        "max_leverage": 2.0,
        "spread_bps": 5.0,
        "demo": {"anchor_price": 0.6458, "daily_vol": 0.075, "daily_volume_usd": 7.0e7, "drift": 0.0003},
    },
    {
        "symbol": "JUP/USDT",
        "name": "Jupiter",
        "asset_class": "crypto",
        "category": "defi",
        "sector": "DEX aggregator",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "JUP",
        "aliases": ["jupusdt", "jup", "jupiter", "юпитер"],
        "popularity": 152,
        "session": "24x7",
        "description": "DEX агрегатор в екосистемата на Solana.",
        "providers": {"binance": "JUPUSDT"},
        "price_precision": 4,
        "qty_step": 0.1,
        "min_qty": 0.1,
        "max_leverage": 2.0,
        "spread_bps": 7.0,
        "demo": {"anchor_price": 0.1883, "daily_vol": 0.049, "daily_volume_usd": 2.0e7, "drift": 0.0003},
    },
    {
        "symbol": "LDO/USDT",
        "name": "Lido DAO",
        "asset_class": "crypto",
        "category": "defi",
        "sector": "Liquid staking",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "LDO",
        "aliases": ["ldousdt", "ldo", "lido", "lido dao"],
        "popularity": 154,
        "session": "24x7",
        "description": "Governance токен на Lido — услуга за liquid staking на ETH.",
        "providers": {"binance": "LDOUSDT", "twelvedata": "LDO/USD"},
        "price_precision": 4,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 2.0,
        "spread_bps": 7.0,
        "demo": {"anchor_price": 0.5764, "daily_vol": 0.059, "daily_volume_usd": 4.0e7, "drift": 0.0003},
    },
    {
        "symbol": "CRV/USDT",
        "name": "Curve DAO",
        "asset_class": "crypto",
        "category": "defi",
        "sector": "Decentralized exchange",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "CRV",
        "aliases": ["crvusdt", "crv", "curve", "curve dao"],
        "popularity": 156,
        "session": "24x7",
        "description": "Governance токен на Curve — DEX, специализиран в размяна на stablecoins.",
        "providers": {"binance": "CRVUSDT", "twelvedata": "CRV/USD"},
        "price_precision": 4,
        "qty_step": 0.1,
        "min_qty": 0.1,
        "max_leverage": 2.0,
        "spread_bps": 5.0,
        "demo": {"anchor_price": 0.3594, "daily_vol": 0.059, "daily_volume_usd": 6.0e7, "drift": 0.0003},
    },
    {
        "symbol": "QNT/USDT",
        "name": "Quant",
        "asset_class": "crypto",
        "category": "infrastructure",
        "sector": "Interoperability",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "QNT",
        "aliases": ["qntusdt", "qnt", "quant", "overledger"],
        "popularity": 158,
        "session": "24x7",
        "description": "Токенът на Quant — технология за свързване на блокчейни и корпоративни системи.",
        "providers": {"binance": "QNTUSDT", "twelvedata": "QNT/USD"},
        "price_precision": 2,
        "qty_step": 0.001,
        "min_qty": 0.001,
        "max_leverage": 2.0,
        "spread_bps": 10.0,
        "demo": {"anchor_price": 69.52, "daily_vol": 0.041, "daily_volume_usd": 1.0e7, "drift": 0.0003},
    },
    {
        "symbol": "STX/USDT",
        "name": "Stacks",
        "asset_class": "crypto",
        "category": "layer2",
        "sector": "Bitcoin layer",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "STX",
        "aliases": ["stxusdt", "stx", "stacks"],
        "popularity": 160,
        "session": "24x7",
        "description": "Слой за smart contracts, свързан с мрежата на Bitcoin.",
        "providers": {"binance": "STXUSDT"},
        "price_precision": 4,
        "qty_step": 0.1,
        "min_qty": 0.1,
        "max_leverage": 2.0,
        "spread_bps": 10.0,
        "demo": {"anchor_price": 0.2445, "daily_vol": 0.047, "daily_volume_usd": 1.0e7, "drift": 0.0003},
    },
    {
        "symbol": "IMX/USDT",
        "name": "Immutable",
        "asset_class": "crypto",
        "category": "gaming",
        "sector": "Gaming infrastructure",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "IMX",
        "aliases": ["imxusdt", "imx", "immutable", "immutable x"],
        "popularity": 162,
        "session": "24x7",
        "description": "Мрежа за блокчейн игри и NFT, изградена върху Ethereum.",
        "providers": {"binance": "IMXUSDT"},
        "price_precision": 4,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 2.0,
        "spread_bps": 10.0,
        "demo": {"anchor_price": 0.219, "daily_vol": 0.059, "daily_volume_usd": 1.0e7, "drift": 0.0003},
    },
    {
        "symbol": "GRT/USDT",
        "name": "The Graph",
        "asset_class": "crypto",
        "category": "infrastructure",
        "sector": "Data indexing",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "GRT",
        "aliases": ["grtusdt", "grt", "the graph", "graph"],
        "popularity": 164,
        "session": "24x7",
        "description": "Протокол за индексиране и търсене на блокчейн данни.",
        "providers": {"binance": "GRTUSDT", "twelvedata": "GRT/USD"},
        "price_precision": 5,
        "qty_step": 1.0,
        "min_qty": 1.0,
        "max_leverage": 2.0,
        "spread_bps": 10.0,
        "demo": {"anchor_price": 0.03321, "daily_vol": 0.047, "daily_volume_usd": 1.0e7, "drift": 0.0003},
    },
    {
        "symbol": "PYTH/USDT",
        "name": "Pyth Network",
        "asset_class": "crypto",
        "category": "infrastructure",
        "sector": "Oracle network",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "PYTH",
        "aliases": ["pythusdt", "pyth", "pyth network"],
        "popularity": 166,
        "session": "24x7",
        "description": "Oracle мрежа, която доставя пазарни цени в реално време към блокчейн приложения.",
        "providers": {"binance": "PYTHUSDT", "twelvedata": "PYTH/USD"},
        "price_precision": 5,
        "qty_step": 0.1,
        "min_qty": 0.1,
        "max_leverage": 2.0,
        "spread_bps": 10.0,
        "demo": {"anchor_price": 0.0559, "daily_vol": 0.076, "daily_volume_usd": 1.0e7, "drift": 0.0003},
    },
    {
        "symbol": "SAND/USDT",
        "name": "The Sandbox",
        "asset_class": "crypto",
        "category": "gaming",
        "sector": "Metaverse",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "SAND",
        "aliases": ["sandusdt", "sand", "sandbox", "the sandbox"],
        "popularity": 168,
        "session": "24x7",
        "description": "Токенът на метавселената The Sandbox.",
        "providers": {"binance": "SANDUSDT", "twelvedata": "SAND/USD"},
        "price_precision": 5,
        "qty_step": 1.0,
        "min_qty": 1.0,
        "max_leverage": 2.0,
        "spread_bps": 10.0,
        "demo": {"anchor_price": 0.1087, "daily_vol": 0.048, "daily_volume_usd": 1.0e7, "drift": 0.0003},
    },
    {
        "symbol": "MANA/USDT",
        "name": "Decentraland",
        "asset_class": "crypto",
        "category": "gaming",
        "sector": "Metaverse",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "MANA",
        "aliases": ["manausdt", "mana", "decentraland"],
        "popularity": 170,
        "session": "24x7",
        "description": "Токенът на виртуалния свят Decentraland.",
        "providers": {"binance": "MANAUSDT", "twelvedata": "MANA/USD"},
        "price_precision": 4,
        "qty_step": 1.0,
        "min_qty": 1.0,
        "max_leverage": 2.0,
        "spread_bps": 10.0,
        "demo": {"anchor_price": 0.1215, "daily_vol": 0.047, "daily_volume_usd": 1.0e7, "drift": 0.0003},
    },
    {
        "symbol": "AXS/USDT",
        "name": "Axie Infinity",
        "asset_class": "crypto",
        "category": "gaming",
        "sector": "Play-to-earn",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "AXS",
        "aliases": ["axsusdt", "axs", "axie", "axie infinity"],
        "popularity": 172,
        "session": "24x7",
        "description": "Governance токен на играта Axie Infinity.",
        "providers": {"binance": "AXSUSDT", "twelvedata": "AXS/USD"},
        "price_precision": 3,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 2.0,
        "spread_bps": 10.0,
        "demo": {"anchor_price": 0.805, "daily_vol": 0.053, "daily_volume_usd": 9.0e6, "drift": 0.0003},
    },
    {
        "symbol": "GALA/USDT",
        "name": "Gala",
        "asset_class": "crypto",
        "category": "gaming",
        "sector": "Web3 gaming",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "GALA",
        "aliases": ["galausdt", "gala", "gala games"],
        "popularity": 174,
        "session": "24x7",
        "description": "Токенът на платформата за блокчейн игри Gala Games.",
        "providers": {"binance": "GALAUSDT", "twelvedata": "GALA/USD"},
        "price_precision": 6,
        "qty_step": 1.0,
        "min_qty": 1.0,
        "max_leverage": 2.0,
        "spread_bps": 7.0,
        "demo": {"anchor_price": 0.00585, "daily_vol": 0.056, "daily_volume_usd": 3.0e7, "drift": 0.0003},
    },
    {
        "symbol": "PAXG/USDT",
        "name": "PAX Gold",
        "asset_class": "crypto",
        "category": "other",
        "sector": "Tokenized gold",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "PAXG",
        "aliases": ["paxgusdt", "paxg", "pax gold", "tokenized gold", "токенизирано злато"],
        "popularity": 176,
        "session": "24x7",
        "description": "Токен, обезпечен с физическо злато — един токен съответства на една тройунция.",
        "providers": {"binance": "PAXGUSDT", "twelvedata": "PAXG/USD"},
        "price_precision": 2,
        "qty_step": 0.0001,
        "min_qty": 0.0001,
        "max_leverage": 2.0,
        "spread_bps": 4.0,
        "demo": {"anchor_price": 4337.0, "daily_vol": 0.011, "daily_volume_usd": 2.0e8, "drift": 0.0002},
    },
    {
        "symbol": "USDC/USDT",
        "name": "USD Coin / Tether",
        "asset_class": "crypto",
        "category": "stablecoin-pair",
        "sector": "Stablecoins",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "USDC",
        "aliases": ["usdcusdt", "usdc", "usd coin", "stablecoin", "стейбълкойн"],
        "popularity": 180,
        "session": "24x7",
        "description": "Двойка от два stablecoin-а — цената обикновено остава много близо до 1.00.",
        "providers": {"binance": "USDCUSDT"},
        "price_precision": 5,
        "qty_step": 1.0,
        "min_qty": 1.0,
        "max_leverage": 2.0,
        "spread_bps": 1.0,
        "demo": {"anchor_price": 1.0, "daily_vol": 0.0003, "daily_volume_usd": 9.0e9, "drift": 0.0},
    },
    {
        "symbol": "BTC/USD",
        "name": "Bitcoin (USD)",
        "asset_class": "crypto",
        "category": "layer1",
        "sector": "Store of value",
        "industry": "",
        "exchange": "Aggregated",
        "country": "",
        "currency": "USD",
        "base": "BTC",
        "aliases": ["btcusd", "btc", "bitcoin", "биткойн", "xbt"],
        "popularity": 44,
        "session": "24x7",
        "description": "Bitcoin, котиран в щатски долари (USD) вместо в USDT — данни от Twelve Data.",
        "providers": {"twelvedata": "BTC/USD"},
        "price_precision": 2,
        "qty_step": 0.00001,
        "min_qty": 0.00001,
        "max_leverage": 2.0,
        "spread_bps": 1.5,
        "demo": {"anchor_price": 87650.0, "daily_vol": 0.02, "daily_volume_usd": 4.0e9, "drift": 0.0004},
    },
    {
        "symbol": "ETH/USD",
        "name": "Ethereum (USD)",
        "asset_class": "crypto",
        "category": "layer1",
        "sector": "Smart contract platform",
        "industry": "",
        "exchange": "Aggregated",
        "country": "",
        "currency": "USD",
        "base": "ETH",
        "aliases": ["ethusd", "eth", "ethereum", "етериум", "ether"],
        "popularity": 46,
        "session": "24x7",
        "description": "Ethereum, котиран в щатски долари (USD) вместо в USDT — данни от Twelve Data.",
        "providers": {"twelvedata": "ETH/USD"},
        "price_precision": 2,
        "qty_step": 0.0001,
        "min_qty": 0.0001,
        "max_leverage": 2.0,
        "spread_bps": 2.0,
        "demo": {"anchor_price": 2972.0, "daily_vol": 0.036, "daily_volume_usd": 3.0e9, "drift": 0.0004},
    },
    {
        "symbol": "SOL/USD",
        "name": "Solana (USD)",
        "asset_class": "crypto",
        "category": "layer1",
        "sector": "Smart contract platform",
        "industry": "",
        "exchange": "Aggregated",
        "country": "",
        "currency": "USD",
        "base": "SOL",
        "aliases": ["solusd", "sol", "solana", "солана"],
        "popularity": 100,
        "session": "24x7",
        "description": "Solana, котирана в щатски долари (USD) вместо в USDT — данни от Twelve Data.",
        "providers": {"twelvedata": "SOL/USD"},
        "price_precision": 2,
        "qty_step": 0.001,
        "min_qty": 0.001,
        "max_leverage": 2.0,
        "spread_bps": 3.0,
        "demo": {"anchor_price": 124.6, "daily_vol": 0.04, "daily_volume_usd": 1.0e9, "drift": 0.0004},
    },
    {
        "symbol": "BTC/EUR",
        "name": "Bitcoin (EUR)",
        "asset_class": "crypto",
        "category": "layer1",
        "sector": "Store of value",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "EUR",
        "base": "BTC",
        "aliases": ["btceur", "btc", "bitcoin", "биткойн", "биткойн евро"],
        "popularity": 60,
        "session": "24x7",
        "description": "Bitcoin, котиран в евро — удобно за сравнение с цената в USDT.",
        "providers": {"binance": "BTCEUR", "twelvedata": "BTC/EUR"},
        "price_precision": 2,
        "qty_step": 0.00001,
        "min_qty": 0.00001,
        "max_leverage": 2.0,
        "spread_bps": 3.0,
        "demo": {"anchor_price": 74350.0, "daily_vol": 0.018, "daily_volume_usd": 2.0e8, "drift": 0.0004},
    },
    {
        "symbol": "ETH/EUR",
        "name": "Ethereum (EUR)",
        "asset_class": "crypto",
        "category": "layer1",
        "sector": "Smart contract platform",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "EUR",
        "base": "ETH",
        "aliases": ["etheur", "eth", "ethereum", "етериум", "етериум евро"],
        "popularity": 102,
        "session": "24x7",
        "description": "Ethereum, котиран в евро — удобно за сравнение с цената в USDT.",
        "providers": {"binance": "ETHEUR", "twelvedata": "ETH/EUR"},
        "price_precision": 2,
        "qty_step": 0.0001,
        "min_qty": 0.0001,
        "max_leverage": 2.0,
        "spread_bps": 4.0,
        "demo": {"anchor_price": 2521.0, "daily_vol": 0.034, "daily_volume_usd": 2.0e8, "drift": 0.0004},
    },
    {
        "symbol": "ETH/BTC",
        "name": "Ethereum / Bitcoin",
        "asset_class": "crypto",
        "category": "layer1",
        "sector": "Smart contract platform",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "BTC",
        "base": "ETH",
        "aliases": ["ethbtc", "eth btc", "ethereum bitcoin", "етериум биткойн"],
        "popularity": 104,
        "session": "24x7",
        "description": "Цената на Ethereum, изразена в Bitcoin — показва относителната сила на двата актива.",
        "providers": {"binance": "ETHBTC", "twelvedata": "ETH/BTC"},
        "price_precision": 5,
        "qty_step": 0.0001,
        "min_qty": 0.0001,
        "max_leverage": 2.0,
        "spread_bps": 3.0,
        "demo": {"anchor_price": 0.0339, "daily_vol": 0.023, "daily_volume_usd": 3.0e8, "drift": 0.0},
    },
]

EXISTING_METADATA: dict[str, dict] = {
    "BTC/USDT": {
        "category": "layer1",
        "sector": "Store of value",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "BTC",
        "aliases": ["btcusdt", "btc", "bitcoin", "биткойн", "xbt"],
        "popularity": 1,
        "session": "24x7",
    },
    "ETH/USDT": {
        "category": "layer1",
        "sector": "Smart contract platform",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "ETH",
        "aliases": ["ethusdt", "eth", "ethereum", "етериум", "ether"],
        "popularity": 2,
        "session": "24x7",
    },
    "SOL/USDT": {
        "category": "layer1",
        "sector": "Smart contract platform",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "SOL",
        "aliases": ["solusdt", "sol", "solana", "солана"],
        "popularity": 6,
        "session": "24x7",
    },
    "XRP/USDT": {
        "category": "payments",
        "sector": "Payments",
        "industry": "",
        "exchange": "Binance",
        "country": "",
        "currency": "USDT",
        "base": "XRP",
        "aliases": ["xrpusdt", "xrp", "ripple", "рипъл"],
        "popularity": 9,
        "session": "24x7",
    },
}
