"""US-listed exchange-traded funds (quoted in USD).

Reference data only: plain dict literals, no imports from the app.
Every ``providers["twelvedata"]`` symbol was checked against the Twelve Data
``/etf?country=United States`` reference list, and ``exchange`` is the listing
exchange reported there (NYSE Arca funds are reported as "NYSE").

The ``demo`` block only parameterises the clearly-labelled SYNTHETIC demo data
generator (rough price level around 2026-01-01, typical daily volatility and
turnover) - it is not a source of real market statistics.
"""

ITEMS: list[dict] = [
    {
        "symbol": "SPY",
        "name": "SPDR S&P 500 ETF Trust",
        "asset_class": "etf",
        "category": "broad",
        "sector": "",
        "industry": "",
        "exchange": "NYSE",
        "country": "United States",
        "currency": "USD",
        "base": "SPY",
        "aliases": ["spy", "spdr s&p 500", "s&p 500 etf", "sp500 etf"],
        "popularity": 20,
        "session": "us_equity",
        "description": "Най-старият и най-търгуваният ETF в света, който следва индекса S&P 500.",
        "providers": {"twelvedata": "SPY"},
        "price_precision": 2,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 5.0,
        "spread_bps": 0.5,
        "demo": {"anchor_price": 682.0, "daily_vol": 0.009, "daily_volume_usd": 3.0e10, "drift": 0.0003},
    },
    {
        "symbol": "QQQ",
        "name": "Invesco QQQ Trust",
        "asset_class": "etf",
        "category": "broad",
        "sector": "",
        "industry": "",
        "exchange": "NASDAQ",
        "country": "United States",
        "currency": "USD",
        "base": "QQQ",
        "aliases": ["qqq", "invesco qqq", "nasdaq 100 etf", "nasdaq etf"],
        "popularity": 23,
        "session": "us_equity",
        "description": "ETF, който следва индекса Nasdaq-100 с големите технологични компании.",
        "providers": {"twelvedata": "QQQ"},
        "price_precision": 2,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 5.0,
        "spread_bps": 0.5,
        "demo": {"anchor_price": 614.0, "daily_vol": 0.012, "daily_volume_usd": 2.0e10, "drift": 0.0004},
    },
    {
        "symbol": "VOO",
        "name": "Vanguard S&P 500 ETF",
        "asset_class": "etf",
        "category": "broad",
        "sector": "",
        "industry": "",
        "exchange": "NYSE",
        "country": "United States",
        "currency": "USD",
        "base": "VOO",
        "aliases": ["voo", "vanguard s&p 500", "vanguard 500", "вангард"],
        "popularity": 27,
        "session": "us_equity",
        "description": "ETF на Vanguard с много ниски разходи, който следва индекса S&P 500.",
        "providers": {"twelvedata": "VOO"},
        "price_precision": 2,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 5.0,
        "spread_bps": 0.7,
        "demo": {"anchor_price": 627.0, "daily_vol": 0.009, "daily_volume_usd": 3.0e9, "drift": 0.0003},
    },
    {
        "symbol": "IVV",
        "name": "iShares Core S&P 500 ETF",
        "asset_class": "etf",
        "category": "broad",
        "sector": "",
        "industry": "",
        "exchange": "NYSE",
        "country": "United States",
        "currency": "USD",
        "base": "IVV",
        "aliases": ["ivv", "ishares s&p 500", "ishares core s&p 500"],
        "popularity": 35,
        "session": "us_equity",
        "description": "ETF на iShares (BlackRock) с ниски такси, който следва индекса S&P 500.",
        "providers": {"twelvedata": "IVV"},
        "price_precision": 2,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 5.0,
        "spread_bps": 0.7,
        "demo": {"anchor_price": 685.0, "daily_vol": 0.009, "daily_volume_usd": 3.0e9, "drift": 0.0003},
    },
    {
        "symbol": "VTI",
        "name": "Vanguard Total Stock Market ETF",
        "asset_class": "etf",
        "category": "broad",
        "sector": "",
        "industry": "",
        "exchange": "NYSE",
        "country": "United States",
        "currency": "USD",
        "base": "VTI",
        "aliases": ["vti", "vanguard total stock market", "total stock market", "total market etf"],
        "popularity": 39,
        "session": "us_equity",
        "description": "ETF, който покрива почти целия американски пазар на акции с хиляди компании.",
        "providers": {"twelvedata": "VTI"},
        "price_precision": 2,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 5.0,
        "spread_bps": 0.8,
        "demo": {"anchor_price": 336.0, "daily_vol": 0.0095, "daily_volume_usd": 1.0e9, "drift": 0.0003},
    },
    {
        "symbol": "DIA",
        "name": "SPDR Dow Jones Industrial Average ETF",
        "asset_class": "etf",
        "category": "broad",
        "sector": "",
        "industry": "",
        "exchange": "NYSE",
        "country": "United States",
        "currency": "USD",
        "base": "DIA",
        "aliases": ["dia", "dow jones etf", "dow etf", "diamonds"],
        "popularity": 45,
        "session": "us_equity",
        "description": "ETF, който следва индекса Dow Jones Industrial Average от 30 големи американски компании.",
        "providers": {"twelvedata": "DIA"},
        "price_precision": 2,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 5.0,
        "spread_bps": 1.0,
        "demo": {"anchor_price": 482.0, "daily_vol": 0.0085, "daily_volume_usd": 7.0e8, "drift": 0.0003},
    },
    {
        "symbol": "IWM",
        "name": "iShares Russell 2000 ETF",
        "asset_class": "etf",
        "category": "broad",
        "sector": "",
        "industry": "",
        "exchange": "NYSE",
        "country": "United States",
        "currency": "USD",
        "base": "IWM",
        "aliases": ["iwm", "russell 2000 etf", "small cap etf", "ръсел 2000"],
        "popularity": 49,
        "session": "us_equity",
        "description": "ETF, който следва индекса Russell 2000 на малките американски компании.",
        "providers": {"twelvedata": "IWM"},
        "price_precision": 2,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 5.0,
        "spread_bps": 1.0,
        "demo": {"anchor_price": 246.0, "daily_vol": 0.013, "daily_volume_usd": 6.0e9, "drift": 0.0003},
    },
    {
        "symbol": "VT",
        "name": "Vanguard Total World Stock ETF",
        "asset_class": "etf",
        "category": "broad",
        "sector": "",
        "industry": "",
        "exchange": "NYSE",
        "country": "United States",
        "currency": "USD",
        "base": "VT",
        "aliases": ["vt", "vanguard total world", "total world", "world etf", "световни акции"],
        "popularity": 85,
        "session": "us_equity",
        "description": "ETF, който покрива акции от целия свят — от развитите и развиващите се пазари.",
        "providers": {"twelvedata": "VT"},
        "price_precision": 2,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 5.0,
        "spread_bps": 1.5,
        "demo": {"anchor_price": 140.0, "daily_vol": 0.009, "daily_volume_usd": 2.0e8, "drift": 0.0003},
    },
    {
        "symbol": "SCHD",
        "name": "Schwab U.S. Dividend Equity ETF",
        "asset_class": "etf",
        "category": "broad",
        "sector": "",
        "industry": "",
        "exchange": "NYSE",
        "country": "United States",
        "currency": "USD",
        "base": "SCHD",
        "aliases": ["schd", "schwab dividend", "dividend etf", "дивидентен etf"],
        "popularity": 88,
        "session": "us_equity",
        "description": "ETF от американски компании с устойчиви и растящи дивиденти.",
        "providers": {"twelvedata": "SCHD"},
        "price_precision": 2,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 5.0,
        "spread_bps": 1.5,
        "demo": {"anchor_price": 27.5, "daily_vol": 0.009, "daily_volume_usd": 4.0e8, "drift": 0.0002},
    },
    {
        "symbol": "GLD",
        "name": "SPDR Gold Shares",
        "asset_class": "etf",
        "category": "commodity",
        "sector": "",
        "industry": "",
        "exchange": "NYSE",
        "country": "United States",
        "currency": "USD",
        "base": "GLD",
        "aliases": ["gld", "spdr gold", "gold etf", "злато etf"],
        "popularity": 102,
        "session": "us_equity",
        "description": "ETF, обезпечен с физическо злато в трезори, който следва цената на златото.",
        "providers": {"twelvedata": "GLD"},
        "price_precision": 2,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 5.0,
        "spread_bps": 1.0,
        "demo": {"anchor_price": 396.0, "daily_vol": 0.012, "daily_volume_usd": 3.0e9, "drift": 0.0002},
    },
    {
        "symbol": "IBIT",
        "name": "iShares Bitcoin Trust ETF",
        "asset_class": "etf",
        "category": "crypto",
        "sector": "",
        "industry": "",
        "exchange": "NASDAQ",
        "country": "United States",
        "currency": "USD",
        "base": "IBIT",
        "aliases": ["ibit", "ishares bitcoin", "bitcoin etf", "биткойн etf"],
        "popularity": 103,
        "session": "us_equity",
        "description": "Спот биткойн ETF на BlackRock, който дава експозиция към цената на биткойна чрез борсов инструмент.",
        "providers": {"twelvedata": "IBIT"},
        "price_precision": 2,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 5.0,
        "spread_bps": 2.0,
        "demo": {"anchor_price": 50.0, "daily_vol": 0.03, "daily_volume_usd": 3.0e9, "drift": 0.0005},
    },
    {
        "symbol": "TLT",
        "name": "iShares 20+ Year Treasury Bond ETF",
        "asset_class": "etf",
        "category": "bond",
        "sector": "",
        "industry": "",
        "exchange": "NASDAQ",
        "country": "United States",
        "currency": "USD",
        "base": "TLT",
        "aliases": ["tlt", "20 year treasury", "long term treasuries", "дългосрочни облигации"],
        "popularity": 106,
        "session": "us_equity",
        "description": "Дългосрочни държавни облигации на САЩ — цената им пада, когато лихвите се покачват.",
        "providers": {"twelvedata": "TLT"},
        "price_precision": 2,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 5.0,
        "spread_bps": 1.0,
        "demo": {"anchor_price": 87.0, "daily_vol": 0.009, "daily_volume_usd": 2.0e9, "drift": 0.0001},
    },
    {
        "symbol": "SLV",
        "name": "iShares Silver Trust",
        "asset_class": "etf",
        "category": "commodity",
        "sector": "",
        "industry": "",
        "exchange": "NYSE",
        "country": "United States",
        "currency": "USD",
        "base": "SLV",
        "aliases": ["slv", "ishares silver", "silver etf", "сребро etf"],
        "popularity": 110,
        "session": "us_equity",
        "description": "ETF, обезпечен с физическо сребро, който следва цената на среброто.",
        "providers": {"twelvedata": "SLV"},
        "price_precision": 2,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 5.0,
        "spread_bps": 1.5,
        "demo": {"anchor_price": 64.0, "daily_vol": 0.022, "daily_volume_usd": 1.5e9, "drift": 0.0002},
    },
    {
        "symbol": "SMH",
        "name": "VanEck Semiconductor ETF",
        "asset_class": "etf",
        "category": "sector",
        "sector": "Technology",
        "industry": "",
        "exchange": "NASDAQ",
        "country": "United States",
        "currency": "USD",
        "base": "SMH",
        "aliases": ["smh", "vaneck semiconductor", "semiconductor etf", "chip etf", "полупроводници"],
        "popularity": 112,
        "session": "us_equity",
        "description": "ETF с най-големите производители и проектанти на полупроводници в света.",
        "providers": {"twelvedata": "SMH"},
        "price_precision": 2,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 5.0,
        "spread_bps": 1.5,
        "demo": {"anchor_price": 360.0, "daily_vol": 0.022, "daily_volume_usd": 2.0e9, "drift": 0.0005},
    },
    {
        "symbol": "XLK",
        "name": "Technology Select Sector SPDR Fund",
        "asset_class": "etf",
        "category": "sector",
        "sector": "Technology",
        "industry": "",
        "exchange": "NYSE",
        "country": "United States",
        "currency": "USD",
        "base": "XLK",
        "aliases": ["xlk", "technology etf", "tech etf", "технологичен сектор"],
        "popularity": 114,
        "session": "us_equity",
        "description": "Секторен ETF с технологичните компании от S&P 500.",
        "providers": {"twelvedata": "XLK"},
        "price_precision": 2,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 5.0,
        "spread_bps": 1.5,
        "demo": {"anchor_price": 144.0, "daily_vol": 0.015, "daily_volume_usd": 1.5e9, "drift": 0.0004},
    },
    {
        "symbol": "ETHA",
        "name": "iShares Ethereum Trust ETF",
        "asset_class": "etf",
        "category": "crypto",
        "sector": "",
        "industry": "",
        "exchange": "NASDAQ",
        "country": "United States",
        "currency": "USD",
        "base": "ETHA",
        "aliases": ["etha", "ishares ethereum", "ethereum etf", "етериум etf"],
        "popularity": 116,
        "session": "us_equity",
        "description": "Спот Ethereum ETF на BlackRock, който следва цената на етера и се търгува само в часовете на борсата.",
        "providers": {"twelvedata": "ETHA"},
        "price_precision": 2,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 5.0,
        "spread_bps": 2.5,
        "demo": {"anchor_price": 22.0, "daily_vol": 0.042, "daily_volume_usd": 1.0e9, "drift": 0.0005},
    },
    {
        "symbol": "EEM",
        "name": "iShares MSCI Emerging Markets ETF",
        "asset_class": "etf",
        "category": "international",
        "sector": "",
        "industry": "",
        "exchange": "NYSE",
        "country": "United States",
        "currency": "USD",
        "base": "EEM",
        "aliases": ["eem", "msci emerging markets", "emerging markets etf", "развиващи се пазари"],
        "popularity": 118,
        "session": "us_equity",
        "description": "ETF с акции от развиващите се пазари като Китай, Индия, Тайван и Бразилия.",
        "providers": {"twelvedata": "EEM"},
        "price_precision": 2,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 5.0,
        "spread_bps": 1.5,
        "demo": {"anchor_price": 54.0, "daily_vol": 0.011, "daily_volume_usd": 1.3e9, "drift": 0.0002},
    },
    {
        "symbol": "ARKK",
        "name": "ARK Innovation ETF",
        "asset_class": "etf",
        "category": "thematic",
        "sector": "",
        "industry": "",
        "exchange": "CBOE",
        "country": "United States",
        "currency": "USD",
        "base": "ARKK",
        "aliases": ["arkk", "ark innovation", "cathie wood", "кати ууд"],
        "popularity": 120,
        "session": "us_equity",
        "description": "Активно управляван ETF, инвестиращ в компании за „революционни“ иновации, с висока волатилност.",
        "providers": {"twelvedata": "ARKK"},
        "price_precision": 2,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 5.0,
        "spread_bps": 3.0,
        "demo": {"anchor_price": 75.0, "daily_vol": 0.028, "daily_volume_usd": 4.0e8, "drift": 0.0002},
    },
    {
        "symbol": "USO",
        "name": "United States Oil Fund",
        "asset_class": "etf",
        "category": "commodity",
        "sector": "",
        "industry": "",
        "exchange": "NYSE",
        "country": "United States",
        "currency": "USD",
        "base": "USO",
        "aliases": ["uso", "us oil fund", "oil etf", "петрол etf"],
        "popularity": 122,
        "session": "us_equity",
        "description": "Фонд, който държи фючърси върху петрола WTI и може да се отклонява от спот цената заради ролването на договорите.",
        "providers": {"twelvedata": "USO"},
        "price_precision": 2,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 5.0,
        "spread_bps": 2.0,
        "demo": {"anchor_price": 68.0, "daily_vol": 0.02, "daily_volume_usd": 3.0e8, "drift": 0.0},
    },
    {
        "symbol": "EFA",
        "name": "iShares MSCI EAFE ETF",
        "asset_class": "etf",
        "category": "international",
        "sector": "",
        "industry": "",
        "exchange": "NYSE",
        "country": "United States",
        "currency": "USD",
        "base": "EFA",
        "aliases": ["efa", "msci eafe", "eafe", "developed markets etf"],
        "popularity": 124,
        "session": "us_equity",
        "description": "ETF с акции от развитите пазари извън САЩ и Канада — Европа, Япония и Австралия.",
        "providers": {"twelvedata": "EFA"},
        "price_precision": 2,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 5.0,
        "spread_bps": 1.5,
        "demo": {"anchor_price": 95.0, "daily_vol": 0.009, "daily_volume_usd": 1.0e9, "drift": 0.0002},
    },
    {
        "symbol": "VEA",
        "name": "Vanguard FTSE Developed Markets ETF",
        "asset_class": "etf",
        "category": "international",
        "sector": "",
        "industry": "",
        "exchange": "NYSE",
        "country": "United States",
        "currency": "USD",
        "base": "VEA",
        "aliases": ["vea", "vanguard developed markets", "ftse developed", "развити пазари"],
        "popularity": 126,
        "session": "us_equity",
        "description": "Нискотаксов ETF с акции от развитите пазари извън САЩ.",
        "providers": {"twelvedata": "VEA"},
        "price_precision": 2,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 5.0,
        "spread_bps": 1.5,
        "demo": {"anchor_price": 62.0, "daily_vol": 0.009, "daily_volume_usd": 6.0e8, "drift": 0.0002},
    },
    {
        "symbol": "VWO",
        "name": "Vanguard FTSE Emerging Markets ETF",
        "asset_class": "etf",
        "category": "international",
        "sector": "",
        "industry": "",
        "exchange": "NYSE",
        "country": "United States",
        "currency": "USD",
        "base": "VWO",
        "aliases": ["vwo", "vanguard emerging markets", "ftse emerging"],
        "popularity": 128,
        "session": "us_equity",
        "description": "Нискотаксов ETF с акции от развиващите се пазари.",
        "providers": {"twelvedata": "VWO"},
        "price_precision": 2,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 5.0,
        "spread_bps": 1.5,
        "demo": {"anchor_price": 54.0, "daily_vol": 0.011, "daily_volume_usd": 5.0e8, "drift": 0.0002},
    },
    {
        "symbol": "HYG",
        "name": "iShares iBoxx $ High Yield Corporate Bond ETF",
        "asset_class": "etf",
        "category": "bond",
        "sector": "",
        "industry": "",
        "exchange": "NYSE",
        "country": "United States",
        "currency": "USD",
        "base": "HYG",
        "aliases": ["hyg", "high yield bonds", "junk bonds", "високодоходни облигации"],
        "popularity": 130,
        "session": "us_equity",
        "description": "ETF с корпоративни облигации с висока доходност и по-нисък кредитен рейтинг.",
        "providers": {"twelvedata": "HYG"},
        "price_precision": 2,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 5.0,
        "spread_bps": 1.0,
        "demo": {"anchor_price": 81.0, "daily_vol": 0.003, "daily_volume_usd": 3.0e9, "drift": 0.0001},
    },
    {
        "symbol": "LQD",
        "name": "iShares iBoxx $ Investment Grade Corporate Bond ETF",
        "asset_class": "etf",
        "category": "bond",
        "sector": "",
        "industry": "",
        "exchange": "NYSE",
        "country": "United States",
        "currency": "USD",
        "base": "LQD",
        "aliases": ["lqd", "investment grade bonds", "corporate bonds", "корпоративни облигации"],
        "popularity": 132,
        "session": "us_equity",
        "description": "ETF с корпоративни облигации с инвестиционен кредитен рейтинг от големи американски компании.",
        "providers": {"twelvedata": "LQD"},
        "price_precision": 2,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 5.0,
        "spread_bps": 1.0,
        "demo": {"anchor_price": 110.0, "daily_vol": 0.005, "daily_volume_usd": 2.0e9, "drift": 0.0001},
    },
    {
        "symbol": "BND",
        "name": "Vanguard Total Bond Market ETF",
        "asset_class": "etf",
        "category": "bond",
        "sector": "",
        "industry": "",
        "exchange": "NASDAQ",
        "country": "United States",
        "currency": "USD",
        "base": "BND",
        "aliases": ["bnd", "vanguard total bond", "total bond market", "облигации"],
        "popularity": 134,
        "session": "us_equity",
        "description": "Широко диверсифициран ETF от американски държавни и корпоративни облигации.",
        "providers": {"twelvedata": "BND"},
        "price_precision": 2,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 5.0,
        "spread_bps": 1.0,
        "demo": {"anchor_price": 74.0, "daily_vol": 0.003, "daily_volume_usd": 5.0e8, "drift": 0.0001},
    },
    {
        "symbol": "IEF",
        "name": "iShares 7-10 Year Treasury Bond ETF",
        "asset_class": "etf",
        "category": "bond",
        "sector": "",
        "industry": "",
        "exchange": "NASDAQ",
        "country": "United States",
        "currency": "USD",
        "base": "IEF",
        "aliases": ["ief", "7-10 year treasury", "средносрочни облигации"],
        "popularity": 136,
        "session": "us_equity",
        "description": "ETF със средносрочни държавни облигации на САЩ с матуритет от 7 до 10 години.",
        "providers": {"twelvedata": "IEF"},
        "price_precision": 2,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 5.0,
        "spread_bps": 1.0,
        "demo": {"anchor_price": 96.0, "daily_vol": 0.004, "daily_volume_usd": 6.0e8, "drift": 0.0001},
    },
    {
        "symbol": "SHY",
        "name": "iShares 1-3 Year Treasury Bond ETF",
        "asset_class": "etf",
        "category": "bond",
        "sector": "",
        "industry": "",
        "exchange": "NASDAQ",
        "country": "United States",
        "currency": "USD",
        "base": "SHY",
        "aliases": ["shy", "1-3 year treasury", "short term treasuries", "краткосрочни облигации"],
        "popularity": 138,
        "session": "us_equity",
        "description": "ETF с краткосрочни държавни облигации на САЩ и много ниска волатилност.",
        "providers": {"twelvedata": "SHY"},
        "price_precision": 2,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 5.0,
        "spread_bps": 1.0,
        "demo": {"anchor_price": 83.0, "daily_vol": 0.0012, "daily_volume_usd": 3.0e8, "drift": 0.0001},
    },
    {
        "symbol": "XLF",
        "name": "Financial Select Sector SPDR Fund",
        "asset_class": "etf",
        "category": "sector",
        "sector": "Financials",
        "industry": "",
        "exchange": "NYSE",
        "country": "United States",
        "currency": "USD",
        "base": "XLF",
        "aliases": ["xlf", "financials etf", "bank etf", "финансов сектор"],
        "popularity": 140,
        "session": "us_equity",
        "description": "Секторен ETF с банките, застрахователите и другите финансови компании от S&P 500.",
        "providers": {"twelvedata": "XLF"},
        "price_precision": 2,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 5.0,
        "spread_bps": 1.5,
        "demo": {"anchor_price": 55.0, "daily_vol": 0.011, "daily_volume_usd": 2.0e9, "drift": 0.0003},
    },
    {
        "symbol": "XLE",
        "name": "Energy Select Sector SPDR Fund",
        "asset_class": "etf",
        "category": "sector",
        "sector": "Energy",
        "industry": "",
        "exchange": "NYSE",
        "country": "United States",
        "currency": "USD",
        "base": "XLE",
        "aliases": ["xle", "energy etf", "oil stocks etf", "енергиен сектор"],
        "popularity": 142,
        "session": "us_equity",
        "description": "Секторен ETF с петролните и газовите компании от S&P 500.",
        "providers": {"twelvedata": "XLE"},
        "price_precision": 2,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 5.0,
        "spread_bps": 1.5,
        "demo": {"anchor_price": 45.0, "daily_vol": 0.015, "daily_volume_usd": 1.2e9, "drift": 0.0001},
    },
    {
        "symbol": "XLV",
        "name": "Health Care Select Sector SPDR Fund",
        "asset_class": "etf",
        "category": "sector",
        "sector": "Health Care",
        "industry": "",
        "exchange": "NYSE",
        "country": "United States",
        "currency": "USD",
        "base": "XLV",
        "aliases": ["xlv", "health care etf", "healthcare etf", "здравеопазване"],
        "popularity": 144,
        "session": "us_equity",
        "description": "Секторен ETF с фармацевтичните и здравните компании от S&P 500.",
        "providers": {"twelvedata": "XLV"},
        "price_precision": 2,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 5.0,
        "spread_bps": 1.5,
        "demo": {"anchor_price": 155.0, "daily_vol": 0.01, "daily_volume_usd": 1.0e9, "drift": 0.0002},
    },
    {
        "symbol": "SOXX",
        "name": "iShares Semiconductor ETF",
        "asset_class": "etf",
        "category": "sector",
        "sector": "Technology",
        "industry": "",
        "exchange": "NASDAQ",
        "country": "United States",
        "currency": "USD",
        "base": "SOXX",
        "aliases": ["soxx", "ishares semiconductor", "chips etf", "чипове"],
        "popularity": 146,
        "session": "us_equity",
        "description": "ETF с американски компании за полупроводници.",
        "providers": {"twelvedata": "SOXX"},
        "price_precision": 2,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 5.0,
        "spread_bps": 1.5,
        "demo": {"anchor_price": 290.0, "daily_vol": 0.024, "daily_volume_usd": 8.0e8, "drift": 0.0005},
    },
    {
        "symbol": "UNG",
        "name": "United States Natural Gas Fund",
        "asset_class": "etf",
        "category": "commodity",
        "sector": "",
        "industry": "",
        "exchange": "NYSE",
        "country": "United States",
        "currency": "USD",
        "base": "UNG",
        "aliases": ["ung", "natural gas etf", "природен газ etf"],
        "popularity": 148,
        "session": "us_equity",
        "description": "Фонд с фючърси върху природен газ — много волатилен, а ролването на договорите може да намалява доходността.",
        "providers": {"twelvedata": "UNG"},
        "price_precision": 2,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 5.0,
        "spread_bps": 3.0,
        "demo": {"anchor_price": 13.0, "daily_vol": 0.04, "daily_volume_usd": 3.0e8, "drift": -0.0002},
    },
    {
        "symbol": "XLY",
        "name": "Consumer Discretionary Select Sector SPDR Fund",
        "asset_class": "etf",
        "category": "sector",
        "sector": "Consumer Discretionary",
        "industry": "",
        "exchange": "NYSE",
        "country": "United States",
        "currency": "USD",
        "base": "XLY",
        "aliases": ["xly", "consumer discretionary etf", "неосновно потребление"],
        "popularity": 150,
        "session": "us_equity",
        "description": "Секторен ETF с компании за стоки и услуги извън първа необходимост като Amazon, Tesla и Home Depot.",
        "providers": {"twelvedata": "XLY"},
        "price_precision": 2,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 5.0,
        "spread_bps": 1.5,
        "demo": {"anchor_price": 118.0, "daily_vol": 0.013, "daily_volume_usd": 8.0e8, "drift": 0.0003},
    },
    {
        "symbol": "XLI",
        "name": "Industrial Select Sector SPDR Fund",
        "asset_class": "etf",
        "category": "sector",
        "sector": "Industrials",
        "industry": "",
        "exchange": "NYSE",
        "country": "United States",
        "currency": "USD",
        "base": "XLI",
        "aliases": ["xli", "industrials etf", "индустриален сектор"],
        "popularity": 152,
        "session": "us_equity",
        "description": "Секторен ETF с индустриалните, транспортните и отбранителните компании от S&P 500.",
        "providers": {"twelvedata": "XLI"},
        "price_precision": 2,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 5.0,
        "spread_bps": 1.5,
        "demo": {"anchor_price": 152.0, "daily_vol": 0.011, "daily_volume_usd": 8.0e8, "drift": 0.0003},
    },
    {
        "symbol": "XLP",
        "name": "Consumer Staples Select Sector SPDR Fund",
        "asset_class": "etf",
        "category": "sector",
        "sector": "Consumer Staples",
        "industry": "",
        "exchange": "NYSE",
        "country": "United States",
        "currency": "USD",
        "base": "XLP",
        "aliases": ["xlp", "consumer staples etf", "основно потребление"],
        "popularity": 154,
        "session": "us_equity",
        "description": "Секторен ETF с производителите и търговците на стоки от първа необходимост.",
        "providers": {"twelvedata": "XLP"},
        "price_precision": 2,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 5.0,
        "spread_bps": 1.5,
        "demo": {"anchor_price": 79.0, "daily_vol": 0.008, "daily_volume_usd": 7.0e8, "drift": 0.0002},
    },
    {
        "symbol": "XLU",
        "name": "Utilities Select Sector SPDR Fund",
        "asset_class": "etf",
        "category": "sector",
        "sector": "Utilities",
        "industry": "",
        "exchange": "NYSE",
        "country": "United States",
        "currency": "USD",
        "base": "XLU",
        "aliases": ["xlu", "utilities etf", "комунални услуги"],
        "popularity": 156,
        "session": "us_equity",
        "description": "Секторен ETF с електрическите и комуналните компании — традиционно по-дефанзивен сектор.",
        "providers": {"twelvedata": "XLU"},
        "price_precision": 2,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 5.0,
        "spread_bps": 1.5,
        "demo": {"anchor_price": 43.0, "daily_vol": 0.01, "daily_volume_usd": 9.0e8, "drift": 0.0002},
    },
    {
        "symbol": "XLC",
        "name": "Communication Services Select Sector SPDR Fund",
        "asset_class": "etf",
        "category": "sector",
        "sector": "Communication Services",
        "industry": "",
        "exchange": "NYSE",
        "country": "United States",
        "currency": "USD",
        "base": "XLC",
        "aliases": ["xlc", "communication services etf", "комуникационни услуги"],
        "popularity": 158,
        "session": "us_equity",
        "description": "Секторен ETF с медийни и телекомуникационни компании като Meta, Alphabet и Netflix.",
        "providers": {"twelvedata": "XLC"},
        "price_precision": 2,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 5.0,
        "spread_bps": 1.5,
        "demo": {"anchor_price": 116.0, "daily_vol": 0.013, "daily_volume_usd": 4.0e8, "drift": 0.0003},
    },
    {
        "symbol": "XLB",
        "name": "Materials Select Sector SPDR Fund",
        "asset_class": "etf",
        "category": "sector",
        "sector": "Materials",
        "industry": "",
        "exchange": "NYSE",
        "country": "United States",
        "currency": "USD",
        "base": "XLB",
        "aliases": ["xlb", "materials etf", "материали"],
        "popularity": 160,
        "session": "us_equity",
        "description": "Секторен ETF с химическите, минните и опаковъчните компании от S&P 500.",
        "providers": {"twelvedata": "XLB"},
        "price_precision": 2,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 5.0,
        "spread_bps": 2.0,
        "demo": {"anchor_price": 45.0, "daily_vol": 0.012, "daily_volume_usd": 3.0e8, "drift": 0.0002},
    },
    {
        "symbol": "XLRE",
        "name": "Real Estate Select Sector SPDR Fund",
        "asset_class": "etf",
        "category": "sector",
        "sector": "Real Estate",
        "industry": "",
        "exchange": "NYSE",
        "country": "United States",
        "currency": "USD",
        "base": "XLRE",
        "aliases": ["xlre", "real estate etf", "reit etf", "недвижими имоти"],
        "popularity": 162,
        "session": "us_equity",
        "description": "Секторен ETF с дружествата за недвижими имоти (REIT) от S&P 500.",
        "providers": {"twelvedata": "XLRE"},
        "price_precision": 2,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 5.0,
        "spread_bps": 2.0,
        "demo": {"anchor_price": 40.0, "daily_vol": 0.011, "daily_volume_usd": 2.0e8, "drift": 0.0001},
    },
    {
        "symbol": "VNQ",
        "name": "Vanguard Real Estate ETF",
        "asset_class": "etf",
        "category": "sector",
        "sector": "Real Estate",
        "industry": "",
        "exchange": "NYSE",
        "country": "United States",
        "currency": "USD",
        "base": "VNQ",
        "aliases": ["vnq", "vanguard real estate", "reits", "имоти"],
        "popularity": 164,
        "session": "us_equity",
        "description": "Широко диверсифициран ETF от американски дружества за недвижими имоти (REIT).",
        "providers": {"twelvedata": "VNQ"},
        "price_precision": 2,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 5.0,
        "spread_bps": 1.5,
        "demo": {"anchor_price": 89.0, "daily_vol": 0.011, "daily_volume_usd": 3.0e8, "drift": 0.0001},
    },
]

EXISTING_METADATA: dict[str, dict] = {}
