"""Forex pairs (Twelve Data symbols, validated against /forex_pairs incl. base/quote currency names).

Reference data only: plain dict literals, no imports from the app.
* Leverage follows the ESMA retail rule literally: 30:1 only when both currencies are in
  {USD, EUR, JPY, GBP, CAD, CHF}; every other pair (incl. NZD/USD, AUD crosses and exotics) is 20:1.
* Prices: 5 decimals, 3 for JPY quotes, 4 for high-priced exotics (TRY). Quantity is in units of the base
  currency (min 1,000 = a micro lot, step 100).
* `demo` only parameterises the clearly-labelled SYNTHETIC demo generator: anchor_price is an approximate
  level around 2026-01-01; daily_vol / daily_volume_usd / drift are rough illustrative values, not statistics.
"""

ITEMS: list[dict] = [
    {
        "symbol": "USD/JPY",
        "name": "US Dollar / Japanese Yen",
        "asset_class": "forex",
        "category": "major",
        "sector": "",
        "industry": "",
        "exchange": "FX",
        "country": "",
        "currency": "JPY",
        "base": "USD",
        "aliases": ["usdjpy", "dollar yen", "yen", "japanese yen", "gopher", "долар йена", "йена", "японска йена"],
        "popularity": 5,
        "session": "fx",
        "description": "Втората най-търгувана валутна двойка; чувствителна към разликата в лихвите между САЩ и Япония.",
        "providers": {"twelvedata": "USD/JPY"},
        "price_precision": 3,
        "qty_step": 100.0,
        "min_qty": 1000.0,
        "max_leverage": 30.0,
        "spread_bps": 0.9,
        "demo": {"anchor_price": 156.5, "daily_vol": 0.006, "daily_volume_usd": 8.0e10, "drift": 0.0},
    },
    {
        "symbol": "USD/CHF",
        "name": "US Dollar / Swiss Franc",
        "asset_class": "forex",
        "category": "major",
        "sector": "",
        "industry": "",
        "exchange": "FX",
        "country": "",
        "currency": "CHF",
        "base": "USD",
        "aliases": ["usdchf", "swissy", "swiss franc", "franc", "dollar franc", "долар франк", "швейцарски франк"],
        "popularity": 17,
        "session": "fx",
        "description": "Двойка с швейцарския франк — валута, често разглеждана като 'safe haven'.",
        "providers": {"twelvedata": "USD/CHF"},
        "price_precision": 5,
        "qty_step": 100.0,
        "min_qty": 1000.0,
        "max_leverage": 30.0,
        "spread_bps": 1.3,
        "demo": {"anchor_price": 0.7925, "daily_vol": 0.005, "daily_volume_usd": 2.0e10, "drift": 0.0},
    },
    {
        "symbol": "USD/CAD",
        "name": "US Dollar / Canadian Dollar",
        "asset_class": "forex",
        "category": "major",
        "sector": "",
        "industry": "",
        "exchange": "FX",
        "country": "",
        "currency": "CAD",
        "base": "USD",
        "aliases": ["usdcad", "loonie", "canadian dollar", "dollar cad", "канадски долар"],
        "popularity": 19,
        "session": "fx",
        "description": "Канадският долар често се движи заедно с цената на петрола.",
        "providers": {"twelvedata": "USD/CAD"},
        "price_precision": 5,
        "qty_step": 100.0,
        "min_qty": 1000.0,
        "max_leverage": 30.0,
        "spread_bps": 1.3,
        "demo": {"anchor_price": 1.372, "daily_vol": 0.004, "daily_volume_usd": 3.0e10, "drift": 0.0},
    },
    {
        "symbol": "NZD/USD",
        "name": "New Zealand Dollar / US Dollar",
        "asset_class": "forex",
        "category": "major",
        "sector": "",
        "industry": "",
        "exchange": "FX",
        "country": "",
        "currency": "USD",
        "base": "NZD",
        "aliases": ["nzdusd", "kiwi", "new zealand dollar", "новозеландски долар"],
        "popularity": 27,
        "session": "fx",
        "description": "Новозеландският долар е чувствителен към цените на селскостопанските стоки и към риск апетита.",
        "providers": {"twelvedata": "NZD/USD"},
        "price_precision": 5,
        "qty_step": 100.0,
        "min_qty": 1000.0,
        "max_leverage": 20.0,
        "spread_bps": 1.5,
        "demo": {"anchor_price": 0.577, "daily_vol": 0.007, "daily_volume_usd": 1.0e10, "drift": 0.0},
    },
    {
        "symbol": "EUR/GBP",
        "name": "Euro / British Pound",
        "asset_class": "forex",
        "category": "cross",
        "sector": "",
        "industry": "",
        "exchange": "FX",
        "country": "",
        "currency": "GBP",
        "base": "EUR",
        "aliases": ["eurgbp", "chunnel", "euro pound", "евро паунд"],
        "popularity": 100,
        "session": "fx",
        "description": "Кръстосана двойка без долар — отразява отношенията между еврозоната и Великобритания.",
        "providers": {"twelvedata": "EUR/GBP"},
        "price_precision": 5,
        "qty_step": 100.0,
        "min_qty": 1000.0,
        "max_leverage": 30.0,
        "spread_bps": 1.5,
        "demo": {"anchor_price": 0.8725, "daily_vol": 0.004, "daily_volume_usd": 1.5e10, "drift": 0.0},
    },
    {
        "symbol": "EUR/JPY",
        "name": "Euro / Japanese Yen",
        "asset_class": "forex",
        "category": "cross",
        "sector": "",
        "industry": "",
        "exchange": "FX",
        "country": "",
        "currency": "JPY",
        "base": "EUR",
        "aliases": ["eurjpy", "euro yen", "yuppy", "евро йена"],
        "popularity": 101,
        "session": "fx",
        "description": "Популярна кръстосана двойка, чувствителна към глобалния риск апетит.",
        "providers": {"twelvedata": "EUR/JPY"},
        "price_precision": 3,
        "qty_step": 100.0,
        "min_qty": 1000.0,
        "max_leverage": 30.0,
        "spread_bps": 1.6,
        "demo": {"anchor_price": 184.0, "daily_vol": 0.006, "daily_volume_usd": 1.5e10, "drift": 0.0},
    },
    {
        "symbol": "GBP/JPY",
        "name": "British Pound / Japanese Yen",
        "asset_class": "forex",
        "category": "cross",
        "sector": "",
        "industry": "",
        "exchange": "FX",
        "country": "",
        "currency": "JPY",
        "base": "GBP",
        "aliases": ["gbpjpy", "guppy", "the beast", "pound yen", "паунд йена"],
        "popularity": 103,
        "session": "fx",
        "description": "Известна с високата си волатилност сред основните кръстосани двойки.",
        "providers": {"twelvedata": "GBP/JPY"},
        "price_precision": 3,
        "qty_step": 100.0,
        "min_qty": 1000.0,
        "max_leverage": 30.0,
        "spread_bps": 2.2,
        "demo": {"anchor_price": 210.5, "daily_vol": 0.0075, "daily_volume_usd": 8.0e9, "drift": 0.0},
    },
    {
        "symbol": "EUR/CHF",
        "name": "Euro / Swiss Franc",
        "asset_class": "forex",
        "category": "cross",
        "sector": "",
        "industry": "",
        "exchange": "FX",
        "country": "",
        "currency": "CHF",
        "base": "EUR",
        "aliases": ["eurchf", "euro swissy", "euro franc", "евро франк"],
        "popularity": 107,
        "session": "fx",
        "description": "Обикновено нисковолатилна двойка, повлияна от политиката на Швейцарската национална банка.",
        "providers": {"twelvedata": "EUR/CHF"},
        "price_precision": 5,
        "qty_step": 100.0,
        "min_qty": 1000.0,
        "max_leverage": 30.0,
        "spread_bps": 1.8,
        "demo": {"anchor_price": 0.93, "daily_vol": 0.0035, "daily_volume_usd": 6.0e9, "drift": 0.0},
    },
    {
        "symbol": "AUD/JPY",
        "name": "Australian Dollar / Japanese Yen",
        "asset_class": "forex",
        "category": "cross",
        "sector": "",
        "industry": "",
        "exchange": "FX",
        "country": "",
        "currency": "JPY",
        "base": "AUD",
        "aliases": ["audjpy", "aussie yen", "австралийски долар йена"],
        "popularity": 109,
        "session": "fx",
        "description": "Често се използва като индикатор за риск апетита на пазарите.",
        "providers": {"twelvedata": "AUD/JPY"},
        "price_precision": 3,
        "qty_step": 100.0,
        "min_qty": 1000.0,
        "max_leverage": 20.0,
        "spread_bps": 2.0,
        "demo": {"anchor_price": 104.4, "daily_vol": 0.008, "daily_volume_usd": 5.0e9, "drift": 0.0},
    },
    {
        "symbol": "EUR/AUD",
        "name": "Euro / Australian Dollar",
        "asset_class": "forex",
        "category": "cross",
        "sector": "",
        "industry": "",
        "exchange": "FX",
        "country": "",
        "currency": "AUD",
        "base": "EUR",
        "aliases": ["euraud", "euro aussie", "евро австралийски долар"],
        "popularity": 113,
        "session": "fx",
        "description": "Кръстосана двойка между еврото и чувствителния към суровините австралийски долар.",
        "providers": {"twelvedata": "EUR/AUD"},
        "price_precision": 5,
        "qty_step": 100.0,
        "min_qty": 1000.0,
        "max_leverage": 20.0,
        "spread_bps": 2.2,
        "demo": {"anchor_price": 1.76, "daily_vol": 0.006, "daily_volume_usd": 4.0e9, "drift": 0.0},
    },
    {
        "symbol": "EUR/CAD",
        "name": "Euro / Canadian Dollar",
        "asset_class": "forex",
        "category": "cross",
        "sector": "",
        "industry": "",
        "exchange": "FX",
        "country": "",
        "currency": "CAD",
        "base": "EUR",
        "aliases": ["eurcad", "euro loonie", "евро канадски долар"],
        "popularity": 115,
        "session": "fx",
        "description": "Кръстосана двойка, в която канадският долар е повлиян от цената на петрола.",
        "providers": {"twelvedata": "EUR/CAD"},
        "price_precision": 5,
        "qty_step": 100.0,
        "min_qty": 1000.0,
        "max_leverage": 30.0,
        "spread_bps": 2.2,
        "demo": {"anchor_price": 1.611, "daily_vol": 0.005, "daily_volume_usd": 3.0e9, "drift": 0.0},
    },
    {
        "symbol": "GBP/CHF",
        "name": "British Pound / Swiss Franc",
        "asset_class": "forex",
        "category": "cross",
        "sector": "",
        "industry": "",
        "exchange": "FX",
        "country": "",
        "currency": "CHF",
        "base": "GBP",
        "aliases": ["gbpchf", "pound franc", "паунд франк"],
        "popularity": 117,
        "session": "fx",
        "description": "Кръстосана двойка между британския паунд и швейцарския франк.",
        "providers": {"twelvedata": "GBP/CHF"},
        "price_precision": 5,
        "qty_step": 100.0,
        "min_qty": 1000.0,
        "max_leverage": 30.0,
        "spread_bps": 2.5,
        "demo": {"anchor_price": 1.066, "daily_vol": 0.006, "daily_volume_usd": 2.0e9, "drift": 0.0},
    },
    {
        "symbol": "CAD/JPY",
        "name": "Canadian Dollar / Japanese Yen",
        "asset_class": "forex",
        "category": "cross",
        "sector": "",
        "industry": "",
        "exchange": "FX",
        "country": "",
        "currency": "JPY",
        "base": "CAD",
        "aliases": ["cadjpy", "loonie yen", "канадски долар йена"],
        "popularity": 119,
        "session": "fx",
        "description": "Кръстосана двойка, повлияна едновременно от петрола и от японските лихви.",
        "providers": {"twelvedata": "CAD/JPY"},
        "price_precision": 3,
        "qty_step": 100.0,
        "min_qty": 1000.0,
        "max_leverage": 30.0,
        "spread_bps": 2.5,
        "demo": {"anchor_price": 114.1, "daily_vol": 0.007, "daily_volume_usd": 2.0e9, "drift": 0.0},
    },
    {
        "symbol": "CHF/JPY",
        "name": "Swiss Franc / Japanese Yen",
        "asset_class": "forex",
        "category": "cross",
        "sector": "",
        "industry": "",
        "exchange": "FX",
        "country": "",
        "currency": "JPY",
        "base": "CHF",
        "aliases": ["chfjpy", "swissy yen", "франк йена"],
        "popularity": 121,
        "session": "fx",
        "description": "Двойка от две валути, традиционно смятани за 'safe haven'.",
        "providers": {"twelvedata": "CHF/JPY"},
        "price_precision": 3,
        "qty_step": 100.0,
        "min_qty": 1000.0,
        "max_leverage": 30.0,
        "spread_bps": 2.5,
        "demo": {"anchor_price": 197.5, "daily_vol": 0.006, "daily_volume_usd": 2.0e9, "drift": 0.0},
    },
    {
        "symbol": "NZD/JPY",
        "name": "New Zealand Dollar / Japanese Yen",
        "asset_class": "forex",
        "category": "cross",
        "sector": "",
        "industry": "",
        "exchange": "FX",
        "country": "",
        "currency": "JPY",
        "base": "NZD",
        "aliases": ["nzdjpy", "kiwi yen", "новозеландски долар йена"],
        "popularity": 123,
        "session": "fx",
        "description": "Кръстосана двойка, чувствителна към риск апетита на пазарите.",
        "providers": {"twelvedata": "NZD/JPY"},
        "price_precision": 3,
        "qty_step": 100.0,
        "min_qty": 1000.0,
        "max_leverage": 20.0,
        "spread_bps": 2.8,
        "demo": {"anchor_price": 90.3, "daily_vol": 0.008, "daily_volume_usd": 2.0e9, "drift": 0.0},
    },
    {
        "symbol": "AUD/NZD",
        "name": "Australian Dollar / New Zealand Dollar",
        "asset_class": "forex",
        "category": "cross",
        "sector": "",
        "industry": "",
        "exchange": "FX",
        "country": "",
        "currency": "NZD",
        "base": "AUD",
        "aliases": ["audnzd", "aussie kiwi", "австралийски новозеландски долар"],
        "popularity": 125,
        "session": "fx",
        "description": "Двойка от две съседни икономики — дневните движения обикновено са сравнително малки.",
        "providers": {"twelvedata": "AUD/NZD"},
        "price_precision": 5,
        "qty_step": 100.0,
        "min_qty": 1000.0,
        "max_leverage": 20.0,
        "spread_bps": 2.5,
        "demo": {"anchor_price": 1.156, "daily_vol": 0.004, "daily_volume_usd": 2.0e9, "drift": 0.0},
    },
    {
        "symbol": "GBP/AUD",
        "name": "British Pound / Australian Dollar",
        "asset_class": "forex",
        "category": "cross",
        "sector": "",
        "industry": "",
        "exchange": "FX",
        "country": "",
        "currency": "AUD",
        "base": "GBP",
        "aliases": ["gbpaud", "pound aussie", "паунд австралийски долар"],
        "popularity": 127,
        "session": "fx",
        "description": "Кръстосана двойка с относително широк дневен диапазон.",
        "providers": {"twelvedata": "GBP/AUD"},
        "price_precision": 5,
        "qty_step": 100.0,
        "min_qty": 1000.0,
        "max_leverage": 20.0,
        "spread_bps": 3.0,
        "demo": {"anchor_price": 2.017, "daily_vol": 0.006, "daily_volume_usd": 2.0e9, "drift": 0.0},
    },
    {
        "symbol": "AUD/CAD",
        "name": "Australian Dollar / Canadian Dollar",
        "asset_class": "forex",
        "category": "cross",
        "sector": "",
        "industry": "",
        "exchange": "FX",
        "country": "",
        "currency": "CAD",
        "base": "AUD",
        "aliases": ["audcad", "aussie loonie", "австралийски канадски долар"],
        "popularity": 129,
        "session": "fx",
        "description": "Двойка от две валути, свързани със суровини — метали и петрол.",
        "providers": {"twelvedata": "AUD/CAD"},
        "price_precision": 5,
        "qty_step": 100.0,
        "min_qty": 1000.0,
        "max_leverage": 20.0,
        "spread_bps": 2.8,
        "demo": {"anchor_price": 0.915, "daily_vol": 0.005, "daily_volume_usd": 1.5e9, "drift": 0.0},
    },
    {
        "symbol": "EUR/NZD",
        "name": "Euro / New Zealand Dollar",
        "asset_class": "forex",
        "category": "cross",
        "sector": "",
        "industry": "",
        "exchange": "FX",
        "country": "",
        "currency": "NZD",
        "base": "EUR",
        "aliases": ["eurnzd", "euro kiwi", "евро новозеландски долар"],
        "popularity": 131,
        "session": "fx",
        "description": "Кръстосана двойка между еврото и новозеландския долар.",
        "providers": {"twelvedata": "EUR/NZD"},
        "price_precision": 5,
        "qty_step": 100.0,
        "min_qty": 1000.0,
        "max_leverage": 20.0,
        "spread_bps": 3.0,
        "demo": {"anchor_price": 2.035, "daily_vol": 0.006, "daily_volume_usd": 1.5e9, "drift": 0.0},
    },
    {
        "symbol": "GBP/CAD",
        "name": "British Pound / Canadian Dollar",
        "asset_class": "forex",
        "category": "cross",
        "sector": "",
        "industry": "",
        "exchange": "FX",
        "country": "",
        "currency": "CAD",
        "base": "GBP",
        "aliases": ["gbpcad", "pound loonie", "паунд канадски долар"],
        "popularity": 133,
        "session": "fx",
        "description": "Кръстосана двойка между британския паунд и канадския долар.",
        "providers": {"twelvedata": "GBP/CAD"},
        "price_precision": 5,
        "qty_step": 100.0,
        "min_qty": 1000.0,
        "max_leverage": 30.0,
        "spread_bps": 3.0,
        "demo": {"anchor_price": 1.845, "daily_vol": 0.006, "daily_volume_usd": 1.5e9, "drift": 0.0},
    },
    {
        "symbol": "USD/TRY",
        "name": "US Dollar / Turkish Lira",
        "asset_class": "forex",
        "category": "exotic",
        "sector": "",
        "industry": "",
        "exchange": "FX",
        "country": "",
        "currency": "TRY",
        "base": "USD",
        "aliases": ["usdtry", "turkish lira", "lira", "турска лира", "долар лира"],
        "popularity": 140,
        "session": "fx",
        "description": "Екзотична двойка с турската лира — исторически висока инфлация и широк спред.",
        "providers": {"twelvedata": "USD/TRY"},
        "price_precision": 4,
        "qty_step": 100.0,
        "min_qty": 1000.0,
        "max_leverage": 20.0,
        "spread_bps": 20.0,
        "demo": {"anchor_price": 42.95, "daily_vol": 0.004, "daily_volume_usd": 2.0e9, "drift": 0.0007},
    },
    {
        "symbol": "USD/MXN",
        "name": "US Dollar / Mexican Peso",
        "asset_class": "forex",
        "category": "exotic",
        "sector": "",
        "industry": "",
        "exchange": "FX",
        "country": "",
        "currency": "MXN",
        "base": "USD",
        "aliases": ["usdmxn", "mexican peso", "peso", "мексиканско песо"],
        "popularity": 142,
        "session": "fx",
        "description": "Мексиканското песо е една от най-търгуваните валути на развиващите се пазари.",
        "providers": {"twelvedata": "USD/MXN"},
        "price_precision": 5,
        "qty_step": 100.0,
        "min_qty": 1000.0,
        "max_leverage": 20.0,
        "spread_bps": 8.0,
        "demo": {"anchor_price": 18.0, "daily_vol": 0.008, "daily_volume_usd": 6.0e9, "drift": 0.0},
    },
    {
        "symbol": "USD/ZAR",
        "name": "US Dollar / South African Rand",
        "asset_class": "forex",
        "category": "exotic",
        "sector": "",
        "industry": "",
        "exchange": "FX",
        "country": "",
        "currency": "ZAR",
        "base": "USD",
        "aliases": ["usdzar", "rand", "south african rand", "южноафрикански ранд", "ранд"],
        "popularity": 144,
        "session": "fx",
        "description": "Екзотична двойка с южноафриканския ранд — по-висока волатилност и по-широк спред.",
        "providers": {"twelvedata": "USD/ZAR"},
        "price_precision": 5,
        "qty_step": 100.0,
        "min_qty": 1000.0,
        "max_leverage": 20.0,
        "spread_bps": 10.0,
        "demo": {"anchor_price": 16.6, "daily_vol": 0.009, "daily_volume_usd": 3.0e9, "drift": 0.0},
    },
    {
        "symbol": "USD/CNH",
        "name": "US Dollar / Chinese Yuan (Offshore)",
        "asset_class": "forex",
        "category": "exotic",
        "sector": "",
        "industry": "",
        "exchange": "FX",
        "country": "",
        "currency": "CNH",
        "base": "USD",
        "aliases": ["usdcnh", "yuan", "renminbi", "cnh", "китайски юан", "юан"],
        "popularity": 146,
        "session": "fx",
        "description": "Офшорният китайски юан (CNH), който се търгува извън континентален Китай.",
        "providers": {"twelvedata": "USD/CNH"},
        "price_precision": 5,
        "qty_step": 100.0,
        "min_qty": 1000.0,
        "max_leverage": 20.0,
        "spread_bps": 5.0,
        "demo": {"anchor_price": 6.99, "daily_vol": 0.003, "daily_volume_usd": 2.0e10, "drift": 0.0},
    },
    {
        "symbol": "USD/SEK",
        "name": "US Dollar / Swedish Krona",
        "asset_class": "forex",
        "category": "exotic",
        "sector": "",
        "industry": "",
        "exchange": "FX",
        "country": "",
        "currency": "SEK",
        "base": "USD",
        "aliases": ["usdsek", "stockie", "swedish krona", "шведска крона"],
        "popularity": 150,
        "session": "fx",
        "description": "Двойка с шведската крона — скандинавска валута с по-малък обем от основните.",
        "providers": {"twelvedata": "USD/SEK"},
        "price_precision": 5,
        "qty_step": 100.0,
        "min_qty": 1000.0,
        "max_leverage": 20.0,
        "spread_bps": 6.0,
        "demo": {"anchor_price": 9.2, "daily_vol": 0.007, "daily_volume_usd": 4.0e9, "drift": 0.0},
    },
    {
        "symbol": "USD/NOK",
        "name": "US Dollar / Norwegian Krone",
        "asset_class": "forex",
        "category": "exotic",
        "sector": "",
        "industry": "",
        "exchange": "FX",
        "country": "",
        "currency": "NOK",
        "base": "USD",
        "aliases": ["usdnok", "nokkie", "norwegian krone", "норвежка крона"],
        "popularity": 152,
        "session": "fx",
        "description": "Норвежката крона често реагира на цената на петрола.",
        "providers": {"twelvedata": "USD/NOK"},
        "price_precision": 5,
        "qty_step": 100.0,
        "min_qty": 1000.0,
        "max_leverage": 20.0,
        "spread_bps": 7.0,
        "demo": {"anchor_price": 10.08, "daily_vol": 0.007, "daily_volume_usd": 3.0e9, "drift": 0.0},
    },
    {
        "symbol": "USD/PLN",
        "name": "US Dollar / Polish Zloty",
        "asset_class": "forex",
        "category": "exotic",
        "sector": "",
        "industry": "",
        "exchange": "FX",
        "country": "",
        "currency": "PLN",
        "base": "USD",
        "aliases": ["usdpln", "zloty", "polish zloty", "полска злота", "злота"],
        "popularity": 154,
        "session": "fx",
        "description": "Двойка с полската злота — валута от Централна и Източна Европа.",
        "providers": {"twelvedata": "USD/PLN"},
        "price_precision": 5,
        "qty_step": 100.0,
        "min_qty": 1000.0,
        "max_leverage": 20.0,
        "spread_bps": 7.0,
        "demo": {"anchor_price": 3.6, "daily_vol": 0.006, "daily_volume_usd": 2.0e9, "drift": 0.0},
    },
    {
        "symbol": "USD/SGD",
        "name": "US Dollar / Singapore Dollar",
        "asset_class": "forex",
        "category": "exotic",
        "sector": "",
        "industry": "",
        "exchange": "FX",
        "country": "",
        "currency": "SGD",
        "base": "USD",
        "aliases": ["usdsgd", "singapore dollar", "сингапурски долар"],
        "popularity": 156,
        "session": "fx",
        "description": "Сингапурският долар се управлява от централната банка спрямо кошница от валути.",
        "providers": {"twelvedata": "USD/SGD"},
        "price_precision": 5,
        "qty_step": 100.0,
        "min_qty": 1000.0,
        "max_leverage": 20.0,
        "spread_bps": 5.0,
        "demo": {"anchor_price": 1.286, "daily_vol": 0.003, "daily_volume_usd": 7.0e9, "drift": 0.0},
    },
    {
        "symbol": "USD/HKD",
        "name": "US Dollar / Hong Kong Dollar",
        "asset_class": "forex",
        "category": "exotic",
        "sector": "",
        "industry": "",
        "exchange": "FX",
        "country": "",
        "currency": "HKD",
        "base": "USD",
        "aliases": ["usdhkd", "hong kong dollar", "хонконгски долар"],
        "popularity": 158,
        "session": "fx",
        "description": "Хонконгският долар е обвързан с щатския в тесен коридор (около 7.75–7.85).",
        "providers": {"twelvedata": "USD/HKD"},
        "price_precision": 5,
        "qty_step": 100.0,
        "min_qty": 1000.0,
        "max_leverage": 20.0,
        "spread_bps": 5.0,
        "demo": {"anchor_price": 7.78, "daily_vol": 0.0005, "daily_volume_usd": 1.0e10, "drift": 0.0},
    },
    {
        "symbol": "EUR/TRY",
        "name": "Euro / Turkish Lira",
        "asset_class": "forex",
        "category": "exotic",
        "sector": "",
        "industry": "",
        "exchange": "FX",
        "country": "",
        "currency": "TRY",
        "base": "EUR",
        "aliases": ["eurtry", "euro lira", "евро лира", "турска лира"],
        "popularity": 160,
        "session": "fx",
        "description": "Екзотична двойка евро/турска лира с широк спред.",
        "providers": {"twelvedata": "EUR/TRY"},
        "price_precision": 4,
        "qty_step": 100.0,
        "min_qty": 1000.0,
        "max_leverage": 20.0,
        "spread_bps": 20.0,
        "demo": {"anchor_price": 50.4, "daily_vol": 0.005, "daily_volume_usd": 1.0e9, "drift": 0.0007},
    },
]

EXISTING_METADATA: dict[str, dict] = {
    "EUR/USD": {
        "category": "major",
        "sector": "",
        "industry": "",
        "exchange": "FX",
        "country": "",
        "currency": "USD",
        "base": "EUR",
        "aliases": ["eurusd", "euro", "euro dollar", "fiber", "евро", "евро долар"],
        "popularity": 3,
        "session": "fx",
    },
    "GBP/USD": {
        "category": "major",
        "sector": "",
        "industry": "",
        "exchange": "FX",
        "country": "",
        "currency": "USD",
        "base": "GBP",
        "aliases": ["gbpusd", "cable", "pound", "sterling", "british pound", "паунд", "британски паунд"],
        "popularity": 7,
        "session": "fx",
    },
    "AUD/USD": {
        "category": "major",
        "sector": "",
        "industry": "",
        "exchange": "FX",
        "country": "",
        "currency": "USD",
        "base": "AUD",
        "aliases": ["audusd", "aussie", "australian dollar", "австралийски долар"],
        "popularity": 15,
        "session": "fx",
    },
}
