"""Stock indices as CFDs: $1 per index point, quoted in USD for the simulation (whatever the home currency).

Reference data only: plain dict literals, no imports from the app.
* Twelve Data symbols were matched by name/country against /indices. DJI, RUT, VIX and SMI are NOT listed
  there (the list has no US indices, and SPI20 is a different index than the SMI), so those instruments
  carry no provider mapping and are demo-only.
* `session` follows the cash market of the index, because that is when the index value itself updates.
* Leverage: ESMA 20:1 for the major indices (S&P 500, NASDAQ 100, Dow, DAX, FTSE 100, CAC 40, Euro Stoxx 50,
  Nikkei 225, ASX 200), 10:1 for the rest.
* `demo` only parameterises the clearly-labelled SYNTHETIC demo generator: anchor_price is an approximate
  level around 2026-01-01; daily_vol / daily_volume_usd / drift are rough illustrative values, not statistics.
"""

ITEMS: list[dict] = [
    {
        "symbol": "DJI",
        "name": "Dow Jones Industrial Average",
        "asset_class": "index",
        "category": "us",
        "sector": "",
        "industry": "",
        "exchange": "INDEX",
        "country": "United States",
        "currency": "USD",
        "base": "DJI",
        "aliases": ["dji", "dow", "dow jones", "dow jones industrial average", "djia", "us30", "dow 30", "дау джоунс"],
        "popularity": 8,
        "session": "us_equity",
        "description": "Ценово претеглен индекс на 30 големи американски компании (CFD, $1 на точка, в USD за симулацията).",
        "providers": {},
        "price_precision": 1,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 20.0,
        "spread_bps": 1.2,
        "demo": {"anchor_price": 48000.0, "daily_vol": 0.009, "daily_volume_usd": 1.0e10, "drift": 0.0003},
    },
    {
        "symbol": "RUT",
        "name": "Russell 2000",
        "asset_class": "index",
        "category": "us",
        "sector": "",
        "industry": "",
        "exchange": "INDEX",
        "country": "United States",
        "currency": "USD",
        "base": "RUT",
        "aliases": ["rut", "russell", "russell 2000", "us2000", "small caps", "малки компании"],
        "popularity": 25,
        "session": "us_equity",
        "description": "Индекс на 2000 по-малки американски компании (CFD, $1 на точка, в USD за симулацията).",
        "providers": {},
        "price_precision": 2,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 10.0,
        "spread_bps": 2.0,
        "demo": {"anchor_price": 2480.0, "daily_vol": 0.014, "daily_volume_usd": 5.0e9, "drift": 0.0003},
    },
    {
        "symbol": "VIX",
        "name": "CBOE Volatility Index",
        "asset_class": "index",
        "category": "volatility",
        "sector": "",
        "industry": "",
        "exchange": "INDEX",
        "country": "United States",
        "currency": "USD",
        "base": "VIX",
        "aliases": ["vix", "volatility", "volatility index", "fear index", "индекс на страха", "волатилност"],
        "popularity": 30,
        "session": "us_equity",
        "description": "Индекс на очакваната волатилност на S&P 500, наричан 'индекс на страха' (CFD, $1 на точка, в USD за симулацията).",
        "providers": {},
        "price_precision": 2,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 10.0,
        "spread_bps": 15.0,
        "demo": {"anchor_price": 15.0, "daily_vol": 0.07, "daily_volume_usd": 2.0e9, "drift": 0.0},
    },
    {
        "symbol": "UK100",
        "name": "UK 100 (FTSE 100)",
        "asset_class": "index",
        "category": "europe",
        "sector": "",
        "industry": "",
        "exchange": "INDEX",
        "country": "United Kingdom",
        "currency": "USD",
        "base": "UK100",
        "aliases": ["uk100", "ftse", "ftse 100", "footsie", "uk 100", "великобритания"],
        "popularity": 100,
        "session": "uk_lse",
        "description": "Индексът на 100-те най-големи компании на Лондонската борса (CFD, $1 на точка, в USD за симулацията).",
        "providers": {"twelvedata": "FTSE"},
        "price_precision": 1,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 20.0,
        "spread_bps": 1.5,
        "demo": {"anchor_price": 9900.0, "daily_vol": 0.008, "daily_volume_usd": 5.0e9, "drift": 0.0002},
    },
    {
        "symbol": "EU50",
        "name": "Euro Stoxx 50",
        "asset_class": "index",
        "category": "europe",
        "sector": "",
        "industry": "",
        "exchange": "INDEX",
        "country": "Eurozone",
        "currency": "USD",
        "base": "EU50",
        "aliases": ["eu50", "euro stoxx", "euro stoxx 50", "stoxx 50", "sx5e", "eu 50", "еврозона"],
        "popularity": 104,
        "session": "eu_xetra",
        "description": "Индекс на 50 водещи компании от еврозоната (CFD, $1 на точка, в USD за симулацията).",
        "providers": {"twelvedata": "STOXX50E"},
        "price_precision": 1,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 20.0,
        "spread_bps": 1.5,
        "demo": {"anchor_price": 5790.0, "daily_vol": 0.01, "daily_volume_usd": 8.0e9, "drift": 0.0003},
    },
    {
        "symbol": "JPN225",
        "name": "Japan 225 (Nikkei 225)",
        "asset_class": "index",
        "category": "asia",
        "sector": "",
        "industry": "",
        "exchange": "INDEX",
        "country": "Japan",
        "currency": "USD",
        "base": "JPN225",
        "aliases": ["jpn225", "nikkei", "nikkei 225", "n225", "jp225", "japan 225", "никей", "япония"],
        "popularity": 106,
        "session": "jp_tse",
        "description": "Ценово претеглен индекс на 225 японски компании от Токийската борса (CFD, $1 на точка, в USD за симулацията).",
        "providers": {"twelvedata": "N225"},
        "price_precision": 1,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 20.0,
        "spread_bps": 2.0,
        "demo": {"anchor_price": 50300.0, "daily_vol": 0.013, "daily_volume_usd": 8.0e9, "drift": 0.0003},
    },
    {
        "symbol": "FRA40",
        "name": "France 40 (CAC 40)",
        "asset_class": "index",
        "category": "europe",
        "sector": "",
        "industry": "",
        "exchange": "INDEX",
        "country": "France",
        "currency": "USD",
        "base": "FRA40",
        "aliases": ["fra40", "cac", "cac 40", "france 40", "fr40", "франция"],
        "popularity": 108,
        "session": "eu_euronext",
        "description": "Индексът на 40 водещи френски компании от Euronext Paris (CFD, $1 на точка, в USD за симулацията).",
        "providers": {"twelvedata": "FCHI"},
        "price_precision": 1,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 20.0,
        "spread_bps": 1.5,
        "demo": {"anchor_price": 8150.0, "daily_vol": 0.01, "daily_volume_usd": 4.0e9, "drift": 0.0002},
    },
    {
        "symbol": "HK50",
        "name": "Hong Kong 50 (Hang Seng)",
        "asset_class": "index",
        "category": "asia",
        "sector": "",
        "industry": "",
        "exchange": "INDEX",
        "country": "Hong Kong",
        "currency": "USD",
        "base": "HK50",
        "aliases": ["hk50", "hang seng", "hsi", "hong kong 50", "хонконг", "ханг сенг"],
        "popularity": 112,
        "session": "hk_hkex",
        "description": "Основният индекс на борсата в Хонконг, силно повлиян от китайски компании (CFD, $1 на точка, в USD за симулацията).",
        "providers": {"twelvedata": "HSI"},
        "price_precision": 1,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 10.0,
        "spread_bps": 2.0,
        "demo": {"anchor_price": 25600.0, "daily_vol": 0.014, "daily_volume_usd": 5.0e9, "drift": 0.0002},
    },
    {
        "symbol": "AUS200",
        "name": "Australia 200 (S&P/ASX 200)",
        "asset_class": "index",
        "category": "asia",
        "sector": "",
        "industry": "",
        "exchange": "INDEX",
        "country": "Australia",
        "currency": "USD",
        "base": "AUS200",
        "aliases": ["aus200", "asx", "asx 200", "australia 200", "xjo", "австралия"],
        "popularity": 120,
        "session": "au_asx",
        "description": "Индекс на 200-те най-големи компании на Австралийската борса (CFD, $1 на точка, в USD за симулацията).",
        "providers": {"twelvedata": "AXJO"},
        "price_precision": 1,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 20.0,
        "spread_bps": 1.5,
        "demo": {"anchor_price": 8700.0, "daily_vol": 0.008, "daily_volume_usd": 3.0e9, "drift": 0.0002},
    },
    {
        "symbol": "ESP35",
        "name": "Spain 35 (IBEX 35)",
        "asset_class": "index",
        "category": "europe",
        "sector": "",
        "industry": "",
        "exchange": "INDEX",
        "country": "Spain",
        "currency": "USD",
        "base": "ESP35",
        "aliases": ["esp35", "ibex", "ibex 35", "spain 35", "испания"],
        "popularity": 130,
        "session": "eu_euronext",
        "description": "Основният индекс на испанската борса с голям дял на банките (CFD, $1 на точка, в USD за симулацията).",
        "providers": {"twelvedata": "IBEX"},
        "price_precision": 1,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 10.0,
        "spread_bps": 2.0,
        "demo": {"anchor_price": 17300.0, "daily_vol": 0.01, "daily_volume_usd": 2.0e9, "drift": 0.0003},
    },
    {
        "symbol": "ITA40",
        "name": "Italy 40 (FTSE MIB)",
        "asset_class": "index",
        "category": "europe",
        "sector": "",
        "industry": "",
        "exchange": "INDEX",
        "country": "Italy",
        "currency": "USD",
        "base": "ITA40",
        "aliases": ["ita40", "ftse mib", "mib", "italy 40", "италия"],
        "popularity": 135,
        "session": "eu_euronext",
        "description": "Индексът на 40 водещи компании от Borsa Italiana (CFD, $1 на точка, в USD за симулацията).",
        "providers": {"twelvedata": "FTSEMIB"},
        "price_precision": 1,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 10.0,
        "spread_bps": 2.0,
        "demo": {"anchor_price": 45000.0, "daily_vol": 0.011, "daily_volume_usd": 3.0e9, "drift": 0.0003},
    },
    {
        "symbol": "NLD25",
        "name": "Netherlands 25 (AEX)",
        "asset_class": "index",
        "category": "europe",
        "sector": "",
        "industry": "",
        "exchange": "INDEX",
        "country": "Netherlands",
        "currency": "USD",
        "base": "NLD25",
        "aliases": ["nld25", "aex", "netherlands 25", "нидерландия", "холандия"],
        "popularity": 140,
        "session": "eu_euronext",
        "description": "Индексът на 25 водещи нидерландски компании от Euronext Amsterdam (CFD, $1 на точка, в USD за симулацията).",
        "providers": {"twelvedata": "AEX"},
        "price_precision": 2,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 10.0,
        "spread_bps": 2.0,
        "demo": {"anchor_price": 945.0, "daily_vol": 0.01, "daily_volume_usd": 2.0e9, "drift": 0.0003},
    },
    {
        "symbol": "SUI20",
        "name": "Switzerland 20 (SMI)",
        "asset_class": "index",
        "category": "europe",
        "sector": "",
        "industry": "",
        "exchange": "INDEX",
        "country": "Switzerland",
        "currency": "USD",
        "base": "SUI20",
        "aliases": ["sui20", "smi", "swiss market index", "switzerland 20", "швейцария"],
        "popularity": 145,
        "session": "eu_xetra",
        "description": "Индексът на 20-те най-големи швейцарски компании, сред тях Nestlé, Novartis и Roche (CFD, $1 на точка, в USD за симулацията).",
        "providers": {},
        "price_precision": 1,
        "qty_step": 0.01,
        "min_qty": 0.01,
        "max_leverage": 10.0,
        "spread_bps": 2.0,
        "demo": {"anchor_price": 13250.0, "daily_vol": 0.008, "daily_volume_usd": 3.0e9, "drift": 0.0002},
    },
]

EXISTING_METADATA: dict[str, dict] = {
    "SPX": {
        "category": "us",
        "sector": "",
        "industry": "",
        "exchange": "INDEX",
        "country": "United States",
        "currency": "USD",
        "base": "SPX",
        "aliases": ["spx", "s&p 500", "sp500", "s&p", "us500", "spx500"],
        "popularity": 5,
        "session": "us_equity",
    },
    "NDX": {
        "category": "us",
        "sector": "",
        "industry": "",
        "exchange": "INDEX",
        "country": "United States",
        "currency": "USD",
        "base": "NDX",
        "aliases": ["ndx", "nasdaq", "nasdaq 100", "nasdaq100", "us100", "nas100", "насдак"],
        "popularity": 6,
        "session": "us_equity",
    },
    "GER40": {
        "category": "europe",
        "sector": "",
        "industry": "",
        "exchange": "INDEX",
        "country": "Germany",
        "currency": "USD",
        "base": "GER40",
        "aliases": ["ger40", "dax", "dax 40", "germany 40", "de40", "германия"],
        "popularity": 40,
        "session": "eu_xetra",
    },
}
