"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-06 10:38:58.782236
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('asset_class', sa.String(length=20), nullable=False),
    sa.Column('price_precision', sa.Integer(), nullable=False),
    sa.Column('qty_step', sa.Float(), nullable=False),
    sa.Column('spread_bps', sa.Float(), nullable=False),
    sa.Column('maker_fee', sa.Float(), nullable=False),
    sa.Column('taker_fee', sa.Float(), nullable=False),
    sa.Column('max_leverage', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_symbol'), ['symbol'], unique=True)

    op.create_table('candles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('ts', sa.BigInteger(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timeframe', 'ts', 'source', name='uq_candle')
    )
    with op.batch_alter_table('candles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candles_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_candles_ts'), ['ts'], unique=False)

    op.create_table('indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('ts', sa.BigInteger(), nullable=False),
    sa.Column('values', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_ts', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('indicators', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_indicators_symbol'), ['symbol'], unique=False)

    op.create_table('lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('module', sa.String(length=40), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lessons_module'), ['module'], unique=False)
        batch_op.create_index(batch_op.f('ix_lessons_slug'), ['slug'], unique=True)

    op.create_table('market_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('change_24h_pct', sa.Float(), nullable=True),
    sa.Column('volume_24h', sa.Float(), nullable=True),
    sa.Column('updated_ts', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'source', name='uq_market_data_symbol_source')
    )
    with op.batch_alter_table('market_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_data_symbol'), ['symbol'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('is_guest', sa.Boolean(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('created_ts', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('ai_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('created_ts', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('challenge_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('progress', sa.JSON(), nullable=False),
    sa.Column('completed_ts', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'key', name='uq_challenge_user_key')
    )
    with op.batch_alter_table('challenge_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_challenge_progress_user_id'), ['user_id'], unique=False)

    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.String(length=32), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('timeframe', sa.String(length=8), nullable=True),
    sa.Column('side', sa.String(length=5), nullable=True),
    sa.Column('setup', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('entry', sa.Float(), nullable=True),
    sa.Column('stop', sa.Float(), nullable=True),
    sa.Column('target', sa.Float(), nullable=True),
    sa.Column('emotion', sa.String(length=40), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('result', sa.Float(), nullable=True),
    sa.Column('r_multiple', sa.Float(), nullable=True),
    sa.Column('lesson', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('mistakes', sa.JSON(), nullable=False),
    sa.Column('screenshot', sa.Text(), nullable=True),
    sa.Column('created_ts', sa.BigInteger(), nullable=False),
    sa.Column('updated_ts', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_entries_trade_id'), ['trade_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entries_user_id'), ['user_id'], unique=False)

    op.create_table('learning_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lesson_slug', sa.String(length=80), nullable=False),
    sa.Column('module', sa.String(length=40), nullable=False),
    sa.Column('completed_ts', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'lesson_slug', name='uq_progress_user_lesson')
    )
    with op.batch_alter_table('learning_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_progress_user_id'), ['user_id'], unique=False)

    op.create_table('paper_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('initial_balance', sa.Float(), nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.Column('realized_pnl', sa.Float(), nullable=False),
    sa.Column('fees_paid', sa.Float(), nullable=False),
    sa.Column('leverage', sa.Float(), nullable=False),
    sa.Column('execution', sa.JSON(), nullable=False),
    sa.Column('peak_equity', sa.Float(), nullable=False),
    sa.Column('max_drawdown_pct', sa.Float(), nullable=False),
    sa.Column('rng_counter', sa.Integer(), nullable=False),
    sa.Column('last_synced_ts', sa.BigInteger(), nullable=False),
    sa.Column('created_ts', sa.BigInteger(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paper_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_accounts_user_id'), ['user_id'], unique=False)

    op.create_table('quiz_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(length=40), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('correct', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('created_ts', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_results_module'), ['module'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_results_user_id'), ['user_id'], unique=False)

    op.create_table('risk_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('ts', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('ref_id', sa.String(length=32), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_events_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_events_ts'), ['ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_events_user_id'), ['user_id'], unique=False)

    op.create_table('strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_template', sa.Boolean(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.Column('created_ts', sa.BigInteger(), nullable=False),
    sa.Column('updated_ts', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategies_user_id'), ['user_id'], unique=False)

    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_ts', sa.BigInteger(), nullable=False),
    sa.Column('expires_ts', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('watchlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'symbol', name='uq_watchlist_user_symbol')
    )
    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watchlist_items_user_id'), ['user_id'], unique=False)

    op.create_table('ai_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=12), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_ts', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['ai_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_messages_session_id'), ['session_id'], unique=False)

    op.create_table('backtests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('strategy_name', sa.String(length=120), nullable=False),
    sa.Column('strategy_snapshot', sa.JSON(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('start_ts', sa.BigInteger(), nullable=False),
    sa.Column('end_ts', sa.BigInteger(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('equity_curve', sa.JSON(), nullable=False),
    sa.Column('validation', sa.JSON(), nullable=False),
    sa.Column('data_source', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_ts', sa.BigInteger(), nullable=False),
    sa.Column('finished_ts', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backtests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backtests_user_id'), ['user_id'], unique=False)

    op.create_table('bots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('strategy_snapshot', sa.JSON(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('pause_reason', sa.String(length=255), nullable=True),
    sa.Column('paper_account_id', sa.Integer(), nullable=False),
    sa.Column('run_mode', sa.String(length=12), nullable=False),
    sa.Column('last_processed_ts', sa.BigInteger(), nullable=True),
    sa.Column('last_signal', sa.JSON(), nullable=False),
    sa.Column('runtime', sa.JSON(), nullable=False),
    sa.Column('regime', sa.String(length=32), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_ts', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['paper_account_id'], ['paper_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bots_user_id'), ['user_id'], unique=False)

    op.create_table('paper_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['paper_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paper_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_events_account_id'), ['account_id'], unique=False)

    op.create_table('paper_orders',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('filled_qty', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('avg_fill_price', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('fill_mode', sa.String(length=12), nullable=False),
    sa.Column('position_id', sa.String(length=32), nullable=True),
    sa.Column('reduce_only', sa.Boolean(), nullable=False),
    sa.Column('fees', sa.Float(), nullable=False),
    sa.Column('slippage_cost', sa.Float(), nullable=False),
    sa.Column('reject_reason', sa.String(length=255), nullable=True),
    sa.Column('active_from_ts', sa.BigInteger(), nullable=False),
    sa.Column('created_ts', sa.BigInteger(), nullable=False),
    sa.Column('updated_ts', sa.BigInteger(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['paper_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paper_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_orders_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_orders_status'), ['status'], unique=False)

    op.create_table('paper_positions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=5), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('initial_qty', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('initial_stop', sa.Float(), nullable=True),
    sa.Column('leverage', sa.Float(), nullable=False),
    sa.Column('fees', sa.Float(), nullable=False),
    sa.Column('realized_pnl', sa.Float(), nullable=False),
    sa.Column('mfe', sa.Float(), nullable=False),
    sa.Column('mae', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('sl_history', sa.JSON(), nullable=False),
    sa.Column('active_from_ts', sa.BigInteger(), nullable=False),
    sa.Column('opened_ts', sa.BigInteger(), nullable=False),
    sa.Column('closed_ts', sa.BigInteger(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['paper_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paper_positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_positions_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_positions_status'), ['status'], unique=False)

    op.create_table('paper_trades',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=5), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=False),
    sa.Column('stop_price', sa.Float(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('gross_pnl', sa.Float(), nullable=False),
    sa.Column('fees', sa.Float(), nullable=False),
    sa.Column('net_pnl', sa.Float(), nullable=False),
    sa.Column('risk_amount', sa.Float(), nullable=True),
    sa.Column('r_multiple', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(length=20), nullable=False),
    sa.Column('opened_ts', sa.BigInteger(), nullable=False),
    sa.Column('closed_ts', sa.BigInteger(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['paper_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paper_trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_trades_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_trades_closed_ts'), ['closed_ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_trades_position_id'), ['position_id'], unique=False)

    op.create_table('replay_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('start_ts', sa.BigInteger(), nullable=False),
    sa.Column('cursor_ts', sa.BigInteger(), nullable=False),
    sa.Column('end_ts', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('created_ts', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['paper_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('replay_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_replay_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('strategy_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('block', sa.String(length=20), nullable=False),
    sa.Column('logic', sa.String(length=4), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('left', sa.JSON(), nullable=False),
    sa.Column('op', sa.String(length=16), nullable=False),
    sa.Column('right', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('strategy_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategy_rules_strategy_id'), ['strategy_id'], unique=False)

    op.create_table('backtest_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('backtest_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(length=5), nullable=False),
    sa.Column('entry_ts', sa.BigInteger(), nullable=False),
    sa.Column('exit_ts', sa.BigInteger(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('net_pnl', sa.Float(), nullable=False),
    sa.Column('fees', sa.Float(), nullable=False),
    sa.Column('r_multiple', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(length=20), nullable=False),
    sa.Column('regime', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['backtest_id'], ['backtests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backtest_trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backtest_trades_backtest_id'), ['backtest_id'], unique=False)

    op.create_table('bot_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.BigInteger(), nullable=False),
    sa.Column('level', sa.String(length=8), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bot_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bot_logs_bot_id'), ['bot_id'], unique=False)

    op.create_table('bot_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('started_ts', sa.BigInteger(), nullable=False),
    sa.Column('stopped_ts', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('start_equity', sa.Float(), nullable=False),
    sa.Column('end_equity', sa.Float(), nullable=True),
    sa.Column('trades', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bot_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bot_runs_bot_id'), ['bot_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bot_runs_bot_id'))

    op.drop_table('bot_runs')
    with op.batch_alter_table('bot_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bot_logs_bot_id'))

    op.drop_table('bot_logs')
    with op.batch_alter_table('backtest_trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backtest_trades_backtest_id'))

    op.drop_table('backtest_trades')
    with op.batch_alter_table('strategy_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategy_rules_strategy_id'))

    op.drop_table('strategy_rules')
    with op.batch_alter_table('replay_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_replay_sessions_user_id'))

    op.drop_table('replay_sessions')
    with op.batch_alter_table('paper_trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_trades_position_id'))
        batch_op.drop_index(batch_op.f('ix_paper_trades_closed_ts'))
        batch_op.drop_index(batch_op.f('ix_paper_trades_account_id'))

    op.drop_table('paper_trades')
    with op.batch_alter_table('paper_positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_positions_status'))
        batch_op.drop_index(batch_op.f('ix_paper_positions_account_id'))

    op.drop_table('paper_positions')
    with op.batch_alter_table('paper_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_orders_status'))
        batch_op.drop_index(batch_op.f('ix_paper_orders_account_id'))

    op.drop_table('paper_orders')
    with op.batch_alter_table('paper_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_events_account_id'))

    op.drop_table('paper_events')
    with op.batch_alter_table('bots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bots_user_id'))

    op.drop_table('bots')
    with op.batch_alter_table('backtests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backtests_user_id'))

    op.drop_table('backtests')
    with op.batch_alter_table('ai_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_messages_session_id'))

    op.drop_table('ai_messages')
    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watchlist_items_user_id'))

    op.drop_table('watchlist_items')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_token_hash'))

    op.drop_table('user_sessions')
    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategies_user_id'))

    op.drop_table('strategies')
    with op.batch_alter_table('risk_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_risk_events_ts'))
        batch_op.drop_index(batch_op.f('ix_risk_events_kind'))

    op.drop_table('risk_events')
    with op.batch_alter_table('quiz_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_results_user_id'))
        batch_op.drop_index(batch_op.f('ix_quiz_results_module'))

    op.drop_table('quiz_results')
    with op.batch_alter_table('paper_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_accounts_user_id'))

    op.drop_table('paper_accounts')
    with op.batch_alter_table('learning_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_progress_user_id'))

    op.drop_table('learning_progress')
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_journal_entries_trade_id'))

    op.drop_table('journal_entries')
    with op.batch_alter_table('challenge_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_challenge_progress_user_id'))

    op.drop_table('challenge_progress')
    with op.batch_alter_table('ai_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_sessions_user_id'))

    op.drop_table('ai_sessions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('market_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_data_symbol'))

    op.drop_table('market_data')
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lessons_slug'))
        batch_op.drop_index(batch_op.f('ix_lessons_module'))

    op.drop_table('lessons')
    with op.batch_alter_table('indicators', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_indicators_symbol'))

    op.drop_table('indicators')
    with op.batch_alter_table('candles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candles_ts'))
        batch_op.drop_index(batch_op.f('ix_candles_symbol'))

    op.drop_table('candles')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_symbol'))

    op.drop_table('assets')
    # ### end Alembic commands ###
