"""v2: catalog metadata, favorites/recent, catalog syncs, replay decisions, structure attempts

Autogenerated against a 0001 database, then reviewed:
* every column added to an existing table is nullable or has a server default, so existing rows
  migrate (SQLite via batch mode, PostgreSQL via plain ALTER TABLE ADD COLUMN);
* assets.slug gets a UNIQUE index (NULLs allowed — existing rows are filled by the seed).

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-06 22:44:02.079599
"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_syncs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('started_ts', sa.BigInteger(), nullable=False),
    sa.Column('finished_ts', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=40), nullable=False),
    sa.Column('created_ts', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'symbol', name='uq_favorite_user_symbol')
    )
    with op.batch_alter_table('favorite_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favorite_assets_user_id'), ['user_id'], unique=False)

    op.create_table('recent_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=40), nullable=False),
    sa.Column('viewed_ts', sa.BigInteger(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'symbol', name='uq_recent_user_symbol')
    )
    with op.batch_alter_table('recent_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recent_assets_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recent_assets_viewed_ts'), ['viewed_ts'], unique=False)

    op.create_table('structure_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=40), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('start_ts', sa.BigInteger(), nullable=False),
    sa.Column('end_ts', sa.BigInteger(), nullable=False),
    sa.Column('marks', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('created_ts', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('structure_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_structure_attempts_user_id'), ['user_id'], unique=False)

    op.create_table('replay_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bar_ts', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(length=6), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('stop', sa.Float(), nullable=True),
    sa.Column('target', sa.Float(), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('outcome', sa.JSON(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('created_ts', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['replay_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('replay_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_replay_decisions_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_replay_decisions_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('ai_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mode', sa.String(length=20), nullable=True))

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=32), server_default='', nullable=False))
        batch_op.add_column(sa.Column('sector', sa.String(length=64), server_default='', nullable=False))
        batch_op.add_column(sa.Column('industry', sa.String(length=96), server_default='', nullable=False))
        batch_op.add_column(sa.Column('exchange', sa.String(length=32), server_default='', nullable=False))
        batch_op.add_column(sa.Column('country', sa.String(length=48), server_default='', nullable=False))
        batch_op.add_column(sa.Column('currency', sa.String(length=12), server_default='USD', nullable=False))
        batch_op.add_column(sa.Column('base', sa.String(length=32), server_default='', nullable=False))
        batch_op.add_column(sa.Column('aliases', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('popularity', sa.Integer(), server_default='1000', nullable=False))
        batch_op.add_column(sa.Column('session', sa.String(length=16), server_default='24x7', nullable=False))
        batch_op.add_column(sa.Column('provider_symbols', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('source', sa.String(length=16), server_default='curated', nullable=False))
        batch_op.add_column(sa.Column('slug', sa.String(length=48), nullable=True))
        batch_op.add_column(sa.Column('min_qty', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('demo', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('updated_ts', sa.BigInteger(), server_default='0', nullable=False))
        batch_op.create_index(batch_op.f('ix_assets_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_assets_source'), ['source'], unique=False)

    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exit_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('strategy', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('risk_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_review', sa.JSON(), nullable=True))

    with op.batch_alter_table('replay_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mode', sa.String(length=12), server_default='trade', nullable=False))
        batch_op.add_column(sa.Column('score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('review', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('strategy_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('replay_sessions', schema=None) as batch_op:
        batch_op.drop_column('strategy_id')
        batch_op.drop_column('review')
        batch_op.drop_column('score')
        batch_op.drop_column('mode')

    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_column('ai_review')
        batch_op.drop_column('notes')
        batch_op.drop_column('risk_amount')
        batch_op.drop_column('strategy')
        batch_op.drop_column('exit_price')

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_source'))
        batch_op.drop_index(batch_op.f('ix_assets_slug'))
        batch_op.drop_column('updated_ts')
        batch_op.drop_column('demo')
        batch_op.drop_column('description')
        batch_op.drop_column('min_qty')
        batch_op.drop_column('slug')
        batch_op.drop_column('source')
        batch_op.drop_column('provider_symbols')
        batch_op.drop_column('session')
        batch_op.drop_column('popularity')
        batch_op.drop_column('aliases')
        batch_op.drop_column('base')
        batch_op.drop_column('currency')
        batch_op.drop_column('country')
        batch_op.drop_column('exchange')
        batch_op.drop_column('industry')
        batch_op.drop_column('sector')
        batch_op.drop_column('category')

    with op.batch_alter_table('ai_sessions', schema=None) as batch_op:
        batch_op.drop_column('mode')

    with op.batch_alter_table('replay_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_replay_decisions_user_id'))
        batch_op.drop_index(batch_op.f('ix_replay_decisions_session_id'))

    op.drop_table('replay_decisions')
    with op.batch_alter_table('structure_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_structure_attempts_user_id'))

    op.drop_table('structure_attempts')
    with op.batch_alter_table('recent_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recent_assets_viewed_ts'))
        batch_op.drop_index(batch_op.f('ix_recent_assets_user_id'))

    op.drop_table('recent_assets')
    with op.batch_alter_table('favorite_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favorite_assets_user_id'))

    op.drop_table('favorite_assets')
    op.drop_table('catalog_syncs')
    # ### end Alembic commands ###
