/*
 * GET /strategies/meta as served by the S6 backend (dsl_version 2), captured from the running API; long
 * descriptions are shortened. Used by the pure-logic unit tests.
 */
import type { BuilderMeta } from "../types";

export const META: BuilderMeta = {
  indicators: {
    sma: { params: { period: 20 }, pane: "price", outputs: ["value"] },
    ema: { params: { period: 20 }, pane: "price", outputs: ["value"] },
    bb: { params: { period: 20, mult: 2.0 }, pane: "price", outputs: ["upper", "middle", "lower"] },
    vwap: { params: {}, pane: "price", outputs: ["value"] },
    rsi: { params: { period: 14 }, pane: "separate", outputs: ["value"] },
    macd: { params: { fast: 12, slow: 26, signal: 9 }, pane: "separate", outputs: ["macd", "signal", "hist"] },
    atr: { params: { period: 14 }, pane: "separate", outputs: ["value"] },
    volume_sma: { params: { period: 20 }, pane: "volume", outputs: ["value"] },
    adx: { params: { period: 14 }, pane: "separate", outputs: ["value"] },
    highest: { params: { period: 20 }, pane: "price", outputs: ["value"] },
    lowest: { params: { period: 20 }, pane: "price", outputs: ["value"] },
  },
  operators: ["<", ">", "<=", ">=", "crosses_above", "crosses_below", "is_true", "is_false"],
  price_fields: ["open", "high", "low", "close", "volume"],
  templates: [
    {
      key: "rsi_ema200_volume",
      name: "RSI < 30 + EMA 200 + Volume (пример от спецификацията)",
      description: "Търси силно 'преразпродаден' момент (RSI < 30) САМО когато д",
      timeframe: "1h",
      tags: [],
    },
    {
      key: "ema_cross_trend",
      name: "EMA 20/50 crossover с филтър EMA 200",
      description: "Trend-following: LONG при пресичане на EMA 20 над EMA 50, са",
      timeframe: "4h",
      tags: [],
    },
    {
      key: "bb_mean_reversion",
      name: "Bollinger mean reversion (само в range)",
      description: "Купува връщане над долната лента и продава връщане под горна",
      timeframe: "1h",
      tags: [],
    },
    {
      key: "breakout_volume",
      name: "Breakout на 20-свещен максимум с обем",
      description: "LONG когато close пробие най-високата цена от последните 20 ",
      timeframe: "1h",
      tags: [],
    },
    {
      key: "macd_momentum",
      name: "MACD momentum над EMA 50",
      description: "LONG при пресичане на MACD над signal линията, докато цената",
      timeframe: "1h",
      tags: [],
    },
    {
      key: "trend_momentum_structure",
      name: "Trend + momentum + structure (EMA200, RSI>50, Higher High, Volume>Avg, ATR×2 stop, 2R target)",
      description: "АКО Price > EMA 200 И RSI > 50 И Higher High И Volume > Aver",
      timeframe: "1h",
      tags: ["trend", "momentum", "structure", "volume", "v2"],
    },
  ],
  dsl_version: 2,
  operand_kinds: [
    { kind: "indicator", label: "Indicator", description: "Технически индикатор (EMA, RSI, ATR, …)." },
    { kind: "price", label: "Price", description: "Поле на свещта: open / high / low / close / volume." },
    { kind: "value", label: "Value", description: "Фиксирано число (праг)." },
    { kind: "structure", label: "Structure", group: "structure", description: "Пазарна структура от потвърдени swing точки (1 = да, 0 = не)" },
    { kind: "structure", label: "Candle pattern", group: "candle_pattern", description: "Свещна формация на текущата свещ (1 = да, 0 = не)." },
  ],
  operator_info: [
    { op: "<", label: "<", text: "е под", needs_right: true },
    { op: ">", label: ">", text: "е над", needs_right: true },
    { op: "<=", label: "≤", text: "е под или равно на", needs_right: true },
    { op: ">=", label: "≥", text: "е над или равно на", needs_right: true },
    { op: "crosses_above", label: "crosses above", text: "пресича нагоре", needs_right: true },
    { op: "crosses_below", label: "crosses below", text: "пресича надолу", needs_right: true },
    { op: "is_true", label: "is true", text: "е вярно (стойност > 0)", needs_right: false },
    { op: "is_false", label: "is false", text: "НЕ е вярно (стойност ≤ 0)", needs_right: false },
  ],
  structures: [
    {
      name: "higher_high",
      label: "Higher High",
      group: "structure",
      bias: "long",
      description: "Последният потвърден swing high е по-висок от предходния (HH",
      lesson: "higher-high",
      params: { left: 3, right: 3 },
    },
    {
      name: "higher_low",
      label: "Higher Low",
      group: "structure",
      bias: "long",
      description: "Последният потвърден swing low е по-висок от предходния (HL)",
      lesson: "higher-low",
      params: { left: 3, right: 3 },
    },
    {
      name: "lower_high",
      label: "Lower High",
      group: "structure",
      bias: "short",
      description: "Последният потвърден swing high не е над предходния (LH).",
      lesson: "lower-high",
      params: { left: 3, right: 3 },
    },
    {
      name: "lower_low",
      label: "Lower Low",
      group: "structure",
      bias: "short",
      description: "Последният потвърден swing low не е над предходния (LL).",
      lesson: "lower-low",
      params: { left: 3, right: 3 },
    },
    {
      name: "uptrend",
      label: "Uptrend (HH + HL)",
      group: "structure",
      bias: "long",
      description: "Последните swing точки са Higher High и Higher Low — бича ст",
      lesson: "trend",
      params: { left: 3, right: 3 },
    },
    {
      name: "downtrend",
      label: "Downtrend (LH + LL)",
      group: "structure",
      bias: "short",
      description: "Последните swing точки са Lower High и Lower Low — меча стру",
      lesson: "trend",
      params: { left: 3, right: 3 },
    },
    {
      name: "break_above_swing_high",
      label: "Break above swing high",
      group: "structure",
      bias: "long",
      description: "Close пробива над последния потвърден swing high на тази све",
      lesson: "breakout",
      params: { left: 3, right: 3 },
    },
    {
      name: "break_below_swing_low",
      label: "Break below swing low",
      group: "structure",
      bias: "short",
      description: "Close пробива под последния потвърден swing low на тази свещ",
      lesson: "breakout",
      params: { left: 3, right: 3 },
    },
    {
      name: "inside_bar",
      label: "Inside bar",
      group: "candle_pattern",
      bias: "neutral",
      description: "Цялата свещ (high и low) е в диапазона на предходната — пауз",
      lesson: "consolidation",
      params: {},
    },
    {
      name: "bullish_engulfing",
      label: "Bullish engulfing",
      group: "candle_pattern",
      bias: "long",
      description: "Бичето тяло 'поглъща' тялото на предходната мечя свещ.",
      lesson: "engulfing",
      params: {},
    },
    {
      name: "bearish_engulfing",
      label: "Bearish engulfing",
      group: "candle_pattern",
      bias: "short",
      description: "Мечото тяло 'поглъща' тялото на предходната бича свещ.",
      lesson: "engulfing",
      params: {},
    },
    {
      name: "hammer",
      label: "Hammer",
      group: "candle_pattern",
      bias: "long",
      description: "Дълъг долен wick (≥ 2× тялото) и малък горен — купувачите въ",
      lesson: "hammer",
      params: {},
    },
    {
      name: "shooting_star",
      label: "Shooting star",
      group: "candle_pattern",
      bias: "short",
      description: "Дълъг горен wick (≥ 2× тялото) и малък долен — купувачите бя",
      lesson: "shooting-star",
      params: {},
    },
  ],
  structure_params: {
    defaults: { left: 3, right: 3 },
    min: 1,
    max: 20,
    note: "Swing точка се потвърждава след `right` свещи — затова структурата закъснява, но е без lookahead.",
  },
  presets: [
    {
      key: "price_above_ema200",
      label: "Price > EMA 200",
      group: "trend",
      side: "long",
      condition: {
        left: { kind: "price", field: "close" },
        op: ">",
        right: { kind: "indicator", name: "ema", params: { period: 200 }, output: "value", mult: 1.0, shift: 0 },
      },
    },
    {
      key: "price_below_ema200",
      label: "Price < EMA 200",
      group: "trend",
      side: "short",
      condition: {
        left: { kind: "price", field: "close" },
        op: "<",
        right: { kind: "indicator", name: "ema", params: { period: 200 }, output: "value", mult: 1.0, shift: 0 },
      },
    },
    {
      key: "ema20_cross_up_ema50",
      label: "EMA 20 crosses above EMA 50",
      group: "trend",
      side: "long",
      condition: {
        left: { kind: "indicator", name: "ema", params: { period: 20 }, output: "value", mult: 1.0, shift: 0 },
        op: "crosses_above",
        right: { kind: "indicator", name: "ema", params: { period: 50 }, output: "value", mult: 1.0, shift: 0 },
      },
    },
    {
      key: "ema20_cross_down_ema50",
      label: "EMA 20 crosses below EMA 50",
      group: "trend",
      side: "short",
      condition: {
        left: { kind: "indicator", name: "ema", params: { period: 20 }, output: "value", mult: 1.0, shift: 0 },
        op: "crosses_below",
        right: { kind: "indicator", name: "ema", params: { period: 50 }, output: "value", mult: 1.0, shift: 0 },
      },
    },
    {
      key: "adx_above_25",
      label: "ADX > 25 (има тренд)",
      group: "trend",
      side: "both",
      condition: {
        left: { kind: "indicator", name: "adx", params: { period: 14 }, output: "value", mult: 1.0, shift: 0 },
        op: ">",
        right: { kind: "value", value: 25 },
      },
    },
    {
      key: "rsi_above_50",
      label: "RSI > 50",
      group: "momentum",
      side: "long",
      condition: {
        left: { kind: "indicator", name: "rsi", params: { period: 14 }, output: "value", mult: 1.0, shift: 0 },
        op: ">",
        right: { kind: "value", value: 50 },
      },
    },
    {
      key: "rsi_below_50",
      label: "RSI < 50",
      group: "momentum",
      side: "short",
      condition: {
        left: { kind: "indicator", name: "rsi", params: { period: 14 }, output: "value", mult: 1.0, shift: 0 },
        op: "<",
        right: { kind: "value", value: 50 },
      },
    },
    {
      key: "rsi_below_30",
      label: "RSI < 30 (oversold)",
      group: "momentum",
      side: "long",
      condition: {
        left: { kind: "indicator", name: "rsi", params: { period: 14 }, output: "value", mult: 1.0, shift: 0 },
        op: "<",
        right: { kind: "value", value: 30 },
      },
    },
    {
      key: "rsi_above_70",
      label: "RSI > 70 (overbought)",
      group: "momentum",
      side: "short",
      condition: {
        left: { kind: "indicator", name: "rsi", params: { period: 14 }, output: "value", mult: 1.0, shift: 0 },
        op: ">",
        right: { kind: "value", value: 70 },
      },
    },
    {
      key: "macd_cross_up",
      label: "MACD crosses above signal",
      group: "momentum",
      side: "long",
      condition: {
        left: { kind: "indicator", name: "macd", params: { fast: 12, slow: 26, signal: 9 }, output: "macd", mult: 1.0, shift: 0 },
        op: "crosses_above",
        right: { kind: "indicator", name: "macd", params: { fast: 12, slow: 26, signal: 9 }, output: "signal", mult: 1.0, shift: 0 },
      },
    },
    {
      key: "macd_cross_down",
      label: "MACD crosses below signal",
      group: "momentum",
      side: "short",
      condition: {
        left: { kind: "indicator", name: "macd", params: { fast: 12, slow: 26, signal: 9 }, output: "macd", mult: 1.0, shift: 0 },
        op: "crosses_below",
        right: { kind: "indicator", name: "macd", params: { fast: 12, slow: 26, signal: 9 }, output: "signal", mult: 1.0, shift: 0 },
      },
    },
    {
      key: "higher_high",
      label: "Higher High",
      group: "structure",
      side: "long",
      condition: { left: { kind: "structure", name: "higher_high", params: {} }, op: "is_true" },
    },
    {
      key: "higher_low",
      label: "Higher Low",
      group: "structure",
      side: "long",
      condition: { left: { kind: "structure", name: "higher_low", params: {} }, op: "is_true" },
    },
    {
      key: "lower_high",
      label: "Lower High",
      group: "structure",
      side: "short",
      condition: { left: { kind: "structure", name: "lower_high", params: {} }, op: "is_true" },
    },
    {
      key: "lower_low",
      label: "Lower Low",
      group: "structure",
      side: "short",
      condition: { left: { kind: "structure", name: "lower_low", params: {} }, op: "is_true" },
    },
    {
      key: "uptrend_structure",
      label: "Uptrend (HH + HL)",
      group: "structure",
      side: "long",
      condition: { left: { kind: "structure", name: "uptrend", params: {} }, op: "is_true" },
    },
    {
      key: "downtrend_structure",
      label: "Downtrend (LH + LL)",
      group: "structure",
      side: "short",
      condition: { left: { kind: "structure", name: "downtrend", params: {} }, op: "is_true" },
    },
    {
      key: "break_above_swing_high",
      label: "Break above swing high",
      group: "structure",
      side: "long",
      condition: { left: { kind: "structure", name: "break_above_swing_high", params: {} }, op: "is_true" },
    },
    {
      key: "break_below_swing_low",
      label: "Break below swing low",
      group: "structure",
      side: "short",
      condition: { left: { kind: "structure", name: "break_below_swing_low", params: {} }, op: "is_true" },
    },
    {
      key: "volume_above_average",
      label: "Volume > Average",
      group: "volume",
      side: "both",
      condition: {
        left: { kind: "price", field: "volume" },
        op: ">",
        right: { kind: "indicator", name: "volume_sma", params: { period: 20 }, output: "value", mult: 1.0, shift: 0 },
      },
    },
    {
      key: "volume_spike",
      label: "Volume > 1.5× Average",
      group: "volume",
      side: "both",
      condition: {
        left: { kind: "price", field: "volume" },
        op: ">",
        right: { kind: "indicator", name: "volume_sma", params: { period: 20 }, output: "value", mult: 1.5, shift: 0 },
      },
    },
    {
      key: "bullish_engulfing",
      label: "Bullish engulfing",
      group: "candle_pattern",
      side: "long",
      condition: { left: { kind: "structure", name: "bullish_engulfing", params: {} }, op: "is_true" },
    },
    {
      key: "bearish_engulfing",
      label: "Bearish engulfing",
      group: "candle_pattern",
      side: "short",
      condition: { left: { kind: "structure", name: "bearish_engulfing", params: {} }, op: "is_true" },
    },
    {
      key: "hammer",
      label: "Hammer",
      group: "candle_pattern",
      side: "long",
      condition: { left: { kind: "structure", name: "hammer", params: {} }, op: "is_true" },
    },
    {
      key: "shooting_star",
      label: "Shooting star",
      group: "candle_pattern",
      side: "short",
      condition: { left: { kind: "structure", name: "shooting_star", params: {} }, op: "is_true" },
    },
    {
      key: "inside_bar",
      label: "Inside bar",
      group: "candle_pattern",
      side: "both",
      condition: { left: { kind: "structure", name: "inside_bar", params: {} }, op: "is_true" },
    },
  ],
  logic: [
    { value: "all", label: "AND", text: "всички условия" },
    { value: "any", label: "OR", text: "поне едно условие" },
  ],
  blocks: [
    { key: "entry_long", label: "LONG entry", then: "Potential LONG Setup" },
    { key: "entry_short", label: "SHORT entry", then: "Potential SHORT Setup" },
    { key: "exit_long", label: "Exit LONG", then: "Close LONG" },
    { key: "exit_short", label: "Exit SHORT", then: "Close SHORT" },
  ],
  stop_types: [
    { type: "atr", label: "ATR × n", defaults: { value: 2, atr_period: 14 } },
    { type: "percent", label: "% от цената", defaults: { value: 1 } },
    {
      type: "swing",
      label: "Зад swing low / high",
      defaults: { value: 1, lookback: 10 },
      note: "value е буфер в единици от 0.1% от цената; lookback = брой свещи.",
    },
  ],
  take_profit_types: [
    { type: "r_multiple", label: "n R (Risk × n)", defaults: { value: 2 } },
    { type: "atr", label: "ATR × n", defaults: { value: 3 } },
    { type: "percent", label: "% от цената", defaults: { value: 2 } },
    { type: "none", label: "Без фиксирана цел", defaults: { value: 2 } },
  ],
  regimes: ["TRENDING_UP", "TRENDING_DOWN", "RANGING", "HIGH_VOLATILITY", "LOW_VOLATILITY", "UNCLEAR"],
  disclaimer: "This is a rule-based hypothetical setup, not a guarantee of future price movement.",
};

/** A v1 backend: no operator_info / structures / presets / rule types — the UI must fall back to local defaults. */
export const META_V1: BuilderMeta = {
  indicators: META.indicators,
  operators: ["<", ">", "<=", ">=", "crosses_above", "crosses_below"],
  price_fields: META.price_fields,
  templates: [],
};
